# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1153, 723)
        mainWindow.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        mainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Program/GridCal_icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setIconSize(QtCore.QSize(24, 24))
        mainWindow.setDocumentMode(False)
        mainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_9.setMargin(2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab)
        self.tabWidget_3.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.splitter_3 = QtGui.QSplitter(self.tab_6)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.frame_10 = QtGui.QFrame(self.splitter_3)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridPlot = MatplotlibWidget(self.frame_10)
        self.gridPlot.setObjectName(_fromUtf8("gridPlot"))
        self.verticalLayout_10.addWidget(self.gridPlot)
        self.frame_8 = QtGui.QFrame(self.splitter_3)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.item_table = QtGui.QTableView(self.frame_8)
        self.item_table.setObjectName(_fromUtf8("item_table"))
        self.verticalLayout_6.addWidget(self.item_table)
        self.frame_9 = QtGui.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.horizontalLayout_6.addWidget(self.splitter_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/grid_icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_6, icon1, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frame_2 = QtGui.QFrame(self.tab_7)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.dataStructuresListView = QtGui.QListView(self.frame_2)
        self.dataStructuresListView.setObjectName(_fromUtf8("dataStructuresListView"))
        self.gridLayout_5.addWidget(self.dataStructuresListView, 1, 0, 1, 1)
        self.dataStructureTableView = QtGui.QTableView(self.frame_2)
        self.dataStructureTableView.setObjectName(_fromUtf8("dataStructureTableView"))
        self.gridLayout_5.addWidget(self.dataStructureTableView, 1, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 40)
        self.verticalLayout_8.addWidget(self.frame_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_border_all_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_7, icon2, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_9)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.splitter_4 = QtGui.QSplitter(self.tab_9)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.frame_11 = QtGui.QFrame(self.splitter_4)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.substations_listview = QtGui.QListView(self.frame_11)
        self.substations_listview.setObjectName(_fromUtf8("substations_listview"))
        self.gridLayout_7.addWidget(self.substations_listview, 0, 0, 1, 1)
        self.frame_17 = QtGui.QFrame(self.splitter_4)
        self.frame_17.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_17.setObjectName(_fromUtf8("frame_17"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_17)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_22 = QtGui.QLabel(self.frame_17)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 10, 3, 1, 1)
        self.substation_g = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_g.setDecimals(8)
        self.substation_g.setObjectName(_fromUtf8("substation_g"))
        self.gridLayout_8.addWidget(self.substation_g, 15, 4, 1, 1)
        self.substation_vangle = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_vangle.setMaximum(90.0)
        self.substation_vangle.setObjectName(_fromUtf8("substation_vangle"))
        self.gridLayout_8.addWidget(self.substation_vangle, 4, 4, 1, 1)
        self.substation_b = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_b.setDecimals(8)
        self.substation_b.setObjectName(_fromUtf8("substation_b"))
        self.gridLayout_8.addWidget(self.substation_b, 15, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.frame_17)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 4, 3, 1, 1)
        self.substation_vabs = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_vabs.setMaximum(15.0)
        self.substation_vabs.setObjectName(_fromUtf8("substation_vabs"))
        self.gridLayout_8.addWidget(self.substation_vabs, 4, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.frame_17)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 10, 0, 1, 1)
        self.substation_p = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_p.setDecimals(8)
        self.substation_p.setObjectName(_fromUtf8("substation_p"))
        self.gridLayout_8.addWidget(self.substation_p, 10, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 20, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_17)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame_17)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_8.addWidget(self.label_18, 3, 0, 1, 1)
        self.substation_basekva = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_basekva.setMinimum(0.12)
        self.substation_basekva.setMaximum(999999.0)
        self.substation_basekva.setProperty("value", 135.0)
        self.substation_basekva.setObjectName(_fromUtf8("substation_basekva"))
        self.gridLayout_8.addWidget(self.substation_basekva, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_17)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.frame_17)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_8.addWidget(self.label_29, 7, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.frame_17)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_8.addWidget(self.label_28, 7, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.frame_17)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_8.addWidget(self.label_27, 3, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.frame_17)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_8.addWidget(self.label_26, 4, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.frame_17)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_8.addWidget(self.label_24, 10, 2, 1, 1)
        self.substation_vmin = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_vmin.setMaximum(15.0)
        self.substation_vmin.setObjectName(_fromUtf8("substation_vmin"))
        self.gridLayout_8.addWidget(self.substation_vmin, 7, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.frame_17)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_8.addWidget(self.label_35, 15, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.frame_17)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_8.addWidget(self.label_34, 15, 0, 1, 1)
        self.substation_q = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_q.setDecimals(8)
        self.substation_q.setObjectName(_fromUtf8("substation_q"))
        self.gridLayout_8.addWidget(self.substation_q, 10, 4, 1, 1)
        self.label_20 = QtGui.QLabel(self.frame_17)
        self.label_20.setAutoFillBackground(True)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 9, 0, 1, 6)
        self.label_36 = QtGui.QLabel(self.frame_17)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.label_36.setPalette(palette)
        self.label_36.setAutoFillBackground(True)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_8.addWidget(self.label_36, 14, 0, 1, 6)
        self.label_31 = QtGui.QLabel(self.frame_17)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 7, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.frame_17)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_8.addWidget(self.label_25, 4, 5, 1, 1)
        self.label_23 = QtGui.QLabel(self.frame_17)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 10, 5, 1, 1)
        self.substation_vmax = QtGui.QDoubleSpinBox(self.frame_17)
        self.substation_vmax.setMaximum(15.0)
        self.substation_vmax.setObjectName(_fromUtf8("substation_vmax"))
        self.gridLayout_8.addWidget(self.substation_vmax, 7, 4, 1, 1)
        self.label_30 = QtGui.QLabel(self.frame_17)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_8.addWidget(self.label_30, 7, 5, 1, 1)
        self.label_32 = QtGui.QLabel(self.frame_17)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_8.addWidget(self.label_32, 15, 3, 1, 1)
        self.substation_slack_checkBox = QtGui.QCheckBox(self.frame_17)
        self.substation_slack_checkBox.setObjectName(_fromUtf8("substation_slack_checkBox"))
        self.gridLayout_8.addWidget(self.substation_slack_checkBox, 1, 3, 1, 2)
        self.substation_name = QtGui.QLineEdit(self.frame_17)
        self.substation_name.setObjectName(_fromUtf8("substation_name"))
        self.gridLayout_8.addWidget(self.substation_name, 1, 1, 1, 2)
        self.label_33 = QtGui.QLabel(self.frame_17)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_8.addWidget(self.label_33, 15, 5, 1, 1)
        self.label_47 = QtGui.QLabel(self.frame_17)
        self.label_47.setAutoFillBackground(True)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_8.addWidget(self.label_47, 0, 0, 1, 6)
        self.substation_apply_changes_button = QtGui.QPushButton(self.frame_17)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_mode_edit_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.substation_apply_changes_button.setIcon(icon3)
        self.substation_apply_changes_button.setFlat(True)
        self.substation_apply_changes_button.setObjectName(_fromUtf8("substation_apply_changes_button"))
        self.gridLayout_8.addWidget(self.substation_apply_changes_button, 21, 4, 1, 2)
        self.dispatchable_load_checkBox = QtGui.QCheckBox(self.frame_17)
        self.dispatchable_load_checkBox.setObjectName(_fromUtf8("dispatchable_load_checkBox"))
        self.gridLayout_8.addWidget(self.dispatchable_load_checkBox, 11, 0, 1, 2)
        self.substation_fix_power_checkBox = QtGui.QCheckBox(self.frame_17)
        self.substation_fix_power_checkBox.setObjectName(_fromUtf8("substation_fix_power_checkBox"))
        self.gridLayout_8.addWidget(self.substation_fix_power_checkBox, 12, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.splitter_4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/substation.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_9, icon4, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_10)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.splitter_5 = QtGui.QSplitter(self.tab_10)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.frame_18 = QtGui.QFrame(self.splitter_5)
        self.frame_18.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_18.setObjectName(_fromUtf8("frame_18"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_18)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.connections_listview = QtGui.QListView(self.frame_18)
        self.connections_listview.setObjectName(_fromUtf8("connections_listview"))
        self.gridLayout_9.addWidget(self.connections_listview, 0, 0, 1, 1)
        self.frame_19 = QtGui.QFrame(self.splitter_5)
        self.frame_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_19.setObjectName(_fromUtf8("frame_19"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_19)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.connections_shift = QtGui.QDoubleSpinBox(self.frame_19)
        self.connections_shift.setMinimum(-2.0)
        self.connections_shift.setMaximum(2.0)
        self.connections_shift.setProperty("value", 1.0)
        self.connections_shift.setObjectName(_fromUtf8("connections_shift"))
        self.gridLayout_10.addWidget(self.connections_shift, 17, 1, 1, 1)
        self.connections_status = QtGui.QCheckBox(self.frame_19)
        self.connections_status.setObjectName(_fromUtf8("connections_status"))
        self.gridLayout_10.addWidget(self.connections_status, 4, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.frame_19)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_10.addWidget(self.label_46, 10, 0, 1, 1)
        self.connections_name = QtGui.QLineEdit(self.frame_19)
        self.connections_name.setObjectName(_fromUtf8("connections_name"))
        self.gridLayout_10.addWidget(self.connections_name, 1, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.frame_19)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_10.addWidget(self.label_52, 11, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 19, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.frame_19)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_10.addWidget(self.label_42, 8, 0, 1, 1)
        self.connections_apply_changes_button = QtGui.QPushButton(self.frame_19)
        self.connections_apply_changes_button.setIcon(icon3)
        self.connections_apply_changes_button.setFlat(True)
        self.connections_apply_changes_button.setObjectName(_fromUtf8("connections_apply_changes_button"))
        self.gridLayout_10.addWidget(self.connections_apply_changes_button, 27, 2, 1, 1)
        self.label_43 = QtGui.QLabel(self.frame_19)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_10.addWidget(self.label_43, 15, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.frame_19)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_10.addWidget(self.label_49, 8, 2, 1, 1)
        self.connections_x = QtGui.QDoubleSpinBox(self.frame_19)
        self.connections_x.setDecimals(4)
        self.connections_x.setMaximum(15.0)
        self.connections_x.setObjectName(_fromUtf8("connections_x"))
        self.gridLayout_10.addWidget(self.connections_x, 10, 1, 1, 1)
        self.connections_r = QtGui.QDoubleSpinBox(self.frame_19)
        self.connections_r.setDecimals(4)
        self.connections_r.setMaximum(90.0)
        self.connections_r.setObjectName(_fromUtf8("connections_r"))
        self.gridLayout_10.addWidget(self.connections_r, 8, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.frame_19)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_10.addWidget(self.label_44, 1, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.frame_19)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_10.addWidget(self.label_45, 10, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.frame_19)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_10.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.frame_19)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_10.addWidget(self.label_37, 15, 2, 1, 1)
        self.connections_b = QtGui.QDoubleSpinBox(self.frame_19)
        self.connections_b.setDecimals(4)
        self.connections_b.setMaximum(15.0)
        self.connections_b.setObjectName(_fromUtf8("connections_b"))
        self.gridLayout_10.addWidget(self.connections_b, 11, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.frame_19)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_10.addWidget(self.label_40, 3, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.frame_19)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_10.addWidget(self.label_38, 5, 0, 1, 1)
        self.connections_ratio = QtGui.QDoubleSpinBox(self.frame_19)
        self.connections_ratio.setMinimum(-2.0)
        self.connections_ratio.setMaximum(2.0)
        self.connections_ratio.setProperty("value", 1.0)
        self.connections_ratio.setObjectName(_fromUtf8("connections_ratio"))
        self.gridLayout_10.addWidget(self.connections_ratio, 15, 1, 1, 1)
        self.connections_bus2 = QtGui.QComboBox(self.frame_19)
        self.connections_bus2.setObjectName(_fromUtf8("connections_bus2"))
        self.gridLayout_10.addWidget(self.connections_bus2, 3, 1, 1, 1)
        self.connections_bus1 = QtGui.QComboBox(self.frame_19)
        self.connections_bus1.setObjectName(_fromUtf8("connections_bus1"))
        self.gridLayout_10.addWidget(self.connections_bus1, 2, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.frame_19)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_10.addWidget(self.label_50, 5, 2, 1, 1)
        self.label_51 = QtGui.QLabel(self.frame_19)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_10.addWidget(self.label_51, 11, 0, 1, 1)
        self.frame_22 = QtGui.QFrame(self.frame_19)
        self.frame_22.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_22.setObjectName(_fromUtf8("frame_22"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_22)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.cable_editor_button = QtGui.QPushButton(self.frame_22)
        self.cable_editor_button.setObjectName(_fromUtf8("cable_editor_button"))
        self.horizontalLayout_10.addWidget(self.cable_editor_button)
        self.line_editor_button = QtGui.QPushButton(self.frame_22)
        self.line_editor_button.setObjectName(_fromUtf8("line_editor_button"))
        self.horizontalLayout_10.addWidget(self.line_editor_button)
        self.transformer_editor_button = QtGui.QPushButton(self.frame_22)
        self.transformer_editor_button.setObjectName(_fromUtf8("transformer_editor_button"))
        self.horizontalLayout_10.addWidget(self.transformer_editor_button)
        self.gridLayout_10.addWidget(self.frame_22, 27, 0, 1, 2)
        self.connections_nominal_power = QtGui.QDoubleSpinBox(self.frame_19)
        self.connections_nominal_power.setDecimals(4)
        self.connections_nominal_power.setMaximum(999999.0)
        self.connections_nominal_power.setObjectName(_fromUtf8("connections_nominal_power"))
        self.gridLayout_10.addWidget(self.connections_nominal_power, 5, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.frame_19)
        self.label_48.setAutoFillBackground(True)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_10.addWidget(self.label_48, 0, 0, 1, 3)
        self.label_54 = QtGui.QLabel(self.frame_19)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_10.addWidget(self.label_54, 17, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.frame_19)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_10.addWidget(self.label_53, 17, 2, 1, 1)
        self.horizontalLayout_8.addWidget(self.splitter_5)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/towertrafo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_10, icon5, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_8)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.splitter_6 = QtGui.QSplitter(self.tab_8)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.frame_20 = QtGui.QFrame(self.splitter_6)
        self.frame_20.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_20.setObjectName(_fromUtf8("frame_20"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_20)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.powerplants_listView = QtGui.QListView(self.frame_20)
        self.powerplants_listView.setObjectName(_fromUtf8("powerplants_listView"))
        self.gridLayout_11.addWidget(self.powerplants_listView, 0, 0, 1, 1)
        self.frame_21 = QtGui.QFrame(self.splitter_6)
        self.frame_21.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_21.setObjectName(_fromUtf8("frame_21"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_21)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_76 = QtGui.QLabel(self.frame_21)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_12.addWidget(self.label_76, 16, 5, 1, 1)
        self.label_63 = QtGui.QLabel(self.frame_21)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_12.addWidget(self.label_63, 22, 3, 1, 1)
        self.powerplants_pmax = QtGui.QDoubleSpinBox(self.frame_21)
        self.powerplants_pmax.setDecimals(8)
        self.powerplants_pmax.setMaximum(99999.0)
        self.powerplants_pmax.setObjectName(_fromUtf8("powerplants_pmax"))
        self.gridLayout_12.addWidget(self.powerplants_pmax, 22, 1, 1, 1)
        self.powerplants_pmin = QtGui.QDoubleSpinBox(self.frame_21)
        self.powerplants_pmin.setDecimals(8)
        self.powerplants_pmin.setMinimum(-99999.0)
        self.powerplants_pmin.setMaximum(99999.0)
        self.powerplants_pmin.setObjectName(_fromUtf8("powerplants_pmin"))
        self.gridLayout_12.addWidget(self.powerplants_pmin, 22, 4, 1, 1)
        self.powerplants_qmax = QtGui.QDoubleSpinBox(self.frame_21)
        self.powerplants_qmax.setDecimals(8)
        self.powerplants_qmax.setMaximum(99999.0)
        self.powerplants_qmax.setObjectName(_fromUtf8("powerplants_qmax"))
        self.gridLayout_12.addWidget(self.powerplants_qmax, 16, 1, 1, 1)
        self.label_62 = QtGui.QLabel(self.frame_21)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_12.addWidget(self.label_62, 4, 0, 1, 1)
        self.powerplants_basepower = QtGui.QDoubleSpinBox(self.frame_21)
        self.powerplants_basepower.setDecimals(4)
        self.powerplants_basepower.setMinimum(0.12)
        self.powerplants_basepower.setMaximum(999999.0)
        self.powerplants_basepower.setProperty("value", 100.0)
        self.powerplants_basepower.setObjectName(_fromUtf8("powerplants_basepower"))
        self.gridLayout_12.addWidget(self.powerplants_basepower, 4, 1, 1, 1)
        self.label_61 = QtGui.QLabel(self.frame_21)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_12.addWidget(self.label_61, 11, 0, 1, 1)
        self.powerplants_bus = QtGui.QComboBox(self.frame_21)
        self.powerplants_bus.setObjectName(_fromUtf8("powerplants_bus"))
        self.gridLayout_12.addWidget(self.powerplants_bus, 3, 1, 1, 3)
        self.label_71 = QtGui.QLabel(self.frame_21)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_12.addWidget(self.label_71, 10, 2, 1, 1)
        self.label_74 = QtGui.QLabel(self.frame_21)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_12.addWidget(self.label_74, 16, 2, 1, 1)
        self.label_75 = QtGui.QLabel(self.frame_21)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_12.addWidget(self.label_75, 16, 0, 1, 1)
        self.label_65 = QtGui.QLabel(self.frame_21)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_12.addWidget(self.label_65, 1, 0, 1, 1)
        self.label_68 = QtGui.QLabel(self.frame_21)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_12.addWidget(self.label_68, 4, 2, 1, 1)
        self.label_59 = QtGui.QLabel(self.frame_21)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_12.addWidget(self.label_59, 10, 0, 1, 1)
        self.powerplants_p = QtGui.QDoubleSpinBox(self.frame_21)
        self.powerplants_p.setDecimals(8)
        self.powerplants_p.setMaximum(999999.0)
        self.powerplants_p.setObjectName(_fromUtf8("powerplants_p"))
        self.gridLayout_12.addWidget(self.powerplants_p, 10, 1, 1, 1)
        self.label_69 = QtGui.QLabel(self.frame_21)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_12.addWidget(self.label_69, 11, 2, 1, 1)
        self.powerplants_v = QtGui.QDoubleSpinBox(self.frame_21)
        self.powerplants_v.setMaximum(2.0)
        self.powerplants_v.setProperty("value", 1.0)
        self.powerplants_v.setObjectName(_fromUtf8("powerplants_v"))
        self.gridLayout_12.addWidget(self.powerplants_v, 11, 1, 1, 1)
        self.powerplants_name = QtGui.QLineEdit(self.frame_21)
        self.powerplants_name.setObjectName(_fromUtf8("powerplants_name"))
        self.gridLayout_12.addWidget(self.powerplants_name, 1, 1, 1, 3)
        self.label_67 = QtGui.QLabel(self.frame_21)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_12.addWidget(self.label_67, 22, 0, 1, 1)
        self.label_66 = QtGui.QLabel(self.frame_21)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_12.addWidget(self.label_66, 22, 2, 1, 1)
        self.label_77 = QtGui.QLabel(self.frame_21)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_12.addWidget(self.label_77, 16, 3, 1, 1)
        self.label_39 = QtGui.QLabel(self.frame_21)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_12.addWidget(self.label_39, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem3, 25, 0, 1, 1)
        self.label_70 = QtGui.QLabel(self.frame_21)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_12.addWidget(self.label_70, 22, 5, 1, 1)
        self.powerplants_qmin = QtGui.QDoubleSpinBox(self.frame_21)
        self.powerplants_qmin.setDecimals(8)
        self.powerplants_qmin.setMinimum(-99999.0)
        self.powerplants_qmin.setMaximum(99999.0)
        self.powerplants_qmin.setObjectName(_fromUtf8("powerplants_qmin"))
        self.gridLayout_12.addWidget(self.powerplants_qmin, 16, 4, 1, 1)
        self.label_78 = QtGui.QLabel(self.frame_21)
        self.label_78.setAutoFillBackground(True)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_12.addWidget(self.label_78, 15, 0, 1, 6)
        self.label_60 = QtGui.QLabel(self.frame_21)
        self.label_60.setAutoFillBackground(True)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_12.addWidget(self.label_60, 9, 0, 1, 6)
        self.label_64 = QtGui.QLabel(self.frame_21)
        self.label_64.setAutoFillBackground(True)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_12.addWidget(self.label_64, 0, 0, 1, 6)
        self.powerplants_apply_changes_button = QtGui.QPushButton(self.frame_21)
        self.powerplants_apply_changes_button.setIcon(icon3)
        self.powerplants_apply_changes_button.setFlat(True)
        self.powerplants_apply_changes_button.setObjectName(_fromUtf8("powerplants_apply_changes_button"))
        self.gridLayout_12.addWidget(self.powerplants_apply_changes_button, 26, 4, 1, 2)
        self.powerplants_status = QtGui.QCheckBox(self.frame_21)
        self.powerplants_status.setObjectName(_fromUtf8("powerplants_status"))
        self.gridLayout_12.addWidget(self.powerplants_status, 1, 4, 1, 2)
        self.dispatchable_gen_checkBox = QtGui.QCheckBox(self.frame_21)
        self.dispatchable_gen_checkBox.setObjectName(_fromUtf8("dispatchable_gen_checkBox"))
        self.gridLayout_12.addWidget(self.dispatchable_gen_checkBox, 10, 3, 1, 2)
        self.powerplants_fix_power_checkBox = QtGui.QCheckBox(self.frame_21)
        self.powerplants_fix_power_checkBox.setObjectName(_fromUtf8("powerplants_fix_power_checkBox"))
        self.gridLayout_12.addWidget(self.powerplants_fix_power_checkBox, 11, 3, 1, 1)
        self.horizontalLayout_9.addWidget(self.splitter_6)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/powerplant.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_8, icon6, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.tabWidget_3)
        self.tabWidget.addTab(self.tab, icon1, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_7 = QtGui.QFrame(self.tab_5)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label = QtGui.QLabel(self.frame_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.line = QtGui.QFrame(self.frame_7)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.label_2 = QtGui.QLabel(self.frame_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.solver_comboBox = QtGui.QComboBox(self.frame_7)
        self.solver_comboBox.setObjectName(_fromUtf8("solver_comboBox"))
        self.verticalLayout_7.addWidget(self.solver_comboBox)
        self.frame_13 = QtGui.QFrame(self.frame_7)
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_13)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.frame_13)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.tolerance_spinBox = QtGui.QSpinBox(self.frame_13)
        self.tolerance_spinBox.setMinimum(1)
        self.tolerance_spinBox.setMaximum(20)
        self.tolerance_spinBox.setProperty("value", 3)
        self.tolerance_spinBox.setObjectName(_fromUtf8("tolerance_spinBox"))
        self.gridLayout_4.addWidget(self.tolerance_spinBox, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_13)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.max_iterations_spinBox = QtGui.QSpinBox(self.frame_13)
        self.max_iterations_spinBox.setMinimum(10)
        self.max_iterations_spinBox.setMaximum(300)
        self.max_iterations_spinBox.setObjectName(_fromUtf8("max_iterations_spinBox"))
        self.gridLayout_4.addWidget(self.max_iterations_spinBox, 2, 1, 1, 1)
        self.helm_retry_checkBox = QtGui.QCheckBox(self.frame_13)
        self.helm_retry_checkBox.setChecked(True)
        self.helm_retry_checkBox.setObjectName(_fromUtf8("helm_retry_checkBox"))
        self.gridLayout_4.addWidget(self.helm_retry_checkBox, 4, 0, 1, 2)
        self.control_Q_checkBox = QtGui.QCheckBox(self.frame_13)
        self.control_Q_checkBox.setChecked(True)
        self.control_Q_checkBox.setObjectName(_fromUtf8("control_Q_checkBox"))
        self.gridLayout_4.addWidget(self.control_Q_checkBox, 7, 0, 1, 2)
        self.auto_precision_checkBox = QtGui.QCheckBox(self.frame_13)
        self.auto_precision_checkBox.setObjectName(_fromUtf8("auto_precision_checkBox"))
        self.gridLayout_4.addWidget(self.auto_precision_checkBox, 0, 0, 1, 2)
        self.retry_solver_comboBox = QtGui.QComboBox(self.frame_13)
        self.retry_solver_comboBox.setObjectName(_fromUtf8("retry_solver_comboBox"))
        self.gridLayout_4.addWidget(self.retry_solver_comboBox, 5, 0, 1, 2)
        self.remember_last_solution_checkBox = QtGui.QCheckBox(self.frame_13)
        self.remember_last_solution_checkBox.setChecked(True)
        self.remember_last_solution_checkBox.setObjectName(_fromUtf8("remember_last_solution_checkBox"))
        self.gridLayout_4.addWidget(self.remember_last_solution_checkBox, 6, 0, 1, 2)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.line_2 = QtGui.QFrame(self.frame_7)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_7.addWidget(self.line_2)
        self.freq_assesment_check = QtGui.QCheckBox(self.frame_7)
        self.freq_assesment_check.setObjectName(_fromUtf8("freq_assesment_check"))
        self.verticalLayout_7.addWidget(self.freq_assesment_check)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.frame_14 = QtGui.QFrame(self.tab_5)
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_11 = QtGui.QLabel(self.frame_14)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_12.addWidget(self.label_11)
        self.line_8 = QtGui.QFrame(self.frame_14)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_12.addWidget(self.line_8)
        self.autorepeat_checkBox = QtGui.QCheckBox(self.frame_14)
        self.autorepeat_checkBox.setChecked(True)
        self.autorepeat_checkBox.setObjectName(_fromUtf8("autorepeat_checkBox"))
        self.verticalLayout_12.addWidget(self.autorepeat_checkBox)
        self.line_9 = QtGui.QFrame(self.frame_14)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_12.addWidget(self.line_9)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem5)
        self.horizontalLayout_4.addWidget(self.frame_14)
        self.frame_16 = QtGui.QFrame(self.tab_5)
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_14 = QtGui.QLabel(self.frame_16)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_13.addWidget(self.label_14)
        self.line_10 = QtGui.QFrame(self.frame_16)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_13.addWidget(self.line_10)
        self.montecarlo_radioButton = QtGui.QRadioButton(self.frame_16)
        self.montecarlo_radioButton.setChecked(True)
        self.montecarlo_radioButton.setObjectName(_fromUtf8("montecarlo_radioButton"))
        self.verticalLayout_13.addWidget(self.montecarlo_radioButton)
        self.stochastic_process_radioButton = QtGui.QRadioButton(self.frame_16)
        self.stochastic_process_radioButton.setObjectName(_fromUtf8("stochastic_process_radioButton"))
        self.verticalLayout_13.addWidget(self.stochastic_process_radioButton)
        self.stochastic_collocation_radioButton = QtGui.QRadioButton(self.frame_16)
        self.stochastic_collocation_radioButton.setObjectName(_fromUtf8("stochastic_collocation_radioButton"))
        self.verticalLayout_13.addWidget(self.stochastic_collocation_radioButton)
        self.frame_15 = QtGui.QFrame(self.frame_16)
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_15)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tolerance_stochastic_spinBox = QtGui.QSpinBox(self.frame_15)
        self.tolerance_stochastic_spinBox.setMinimum(1)
        self.tolerance_stochastic_spinBox.setMaximum(20)
        self.tolerance_stochastic_spinBox.setProperty("value", 3)
        self.tolerance_stochastic_spinBox.setObjectName(_fromUtf8("tolerance_stochastic_spinBox"))
        self.gridLayout_6.addWidget(self.tolerance_stochastic_spinBox, 3, 1, 1, 1)
        self.max_iterations_stochastic_spinBox = QtGui.QSpinBox(self.frame_15)
        self.max_iterations_stochastic_spinBox.setMinimum(10)
        self.max_iterations_stochastic_spinBox.setMaximum(99999999)
        self.max_iterations_stochastic_spinBox.setProperty("value", 1000)
        self.max_iterations_stochastic_spinBox.setObjectName(_fromUtf8("max_iterations_stochastic_spinBox"))
        self.gridLayout_6.addWidget(self.max_iterations_stochastic_spinBox, 4, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_15)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame_15)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 3, 0, 1, 1)
        self.group_by_comboBox = QtGui.QComboBox(self.frame_15)
        self.group_by_comboBox.setObjectName(_fromUtf8("group_by_comboBox"))
        self.gridLayout_6.addWidget(self.group_by_comboBox, 1, 0, 1, 2)
        self.label_55 = QtGui.QLabel(self.frame_15)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_6.addWidget(self.label_55, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_15)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.horizontalLayout_4.addWidget(self.frame_16)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_settings_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon7, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget_2 = QtGui.QTabWidget(self.widget)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_6 = QtGui.QFrame(self.tab_4)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.pushButton_3 = QtGui.QPushButton(self.frame_6)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.frame_6)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.tableView_2 = QtGui.QTableView(self.tab_4)
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.verticalLayout_3.addWidget(self.tableView_2)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setContentsMargins(0, 4, 0, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_3 = QtGui.QFrame(self.tab_3)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget_4 = QtGui.QTabWidget(self.frame_3)
        self.tabWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_4.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_11)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.frame = QtGui.QFrame(self.tab_11)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.profile_time_selection_comboBox = QtGui.QComboBox(self.frame)
        self.profile_time_selection_comboBox.setObjectName(_fromUtf8("profile_time_selection_comboBox"))
        self.horizontalLayout.addWidget(self.profile_time_selection_comboBox)
        self.set_profile_state_button = QtGui.QPushButton(self.frame)
        self.set_profile_state_button.setObjectName(_fromUtf8("set_profile_state_button"))
        self.horizontalLayout.addWidget(self.set_profile_state_button)
        self.line_7 = QtGui.QFrame(self.frame)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.visualizeGenButton = QtGui.QPushButton(self.frame)
        self.visualizeGenButton.setObjectName(_fromUtf8("visualizeGenButton"))
        self.horizontalLayout.addWidget(self.visualizeGenButton)
        self.visualizeLoadsButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualizeLoadsButton.sizePolicy().hasHeightForWidth())
        self.visualizeLoadsButton.setSizePolicy(sizePolicy)
        self.visualizeLoadsButton.setObjectName(_fromUtf8("visualizeLoadsButton"))
        self.horizontalLayout.addWidget(self.visualizeLoadsButton)
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.importGenButton = QtGui.QPushButton(self.frame)
        self.importGenButton.setObjectName(_fromUtf8("importGenButton"))
        self.horizontalLayout.addWidget(self.importGenButton)
        self.importLoadButton = QtGui.QPushButton(self.frame)
        self.importLoadButton.setFlat(False)
        self.importLoadButton.setObjectName(_fromUtf8("importLoadButton"))
        self.horizontalLayout.addWidget(self.importLoadButton)
        self.verticalLayout_14.addWidget(self.frame)
        self.tableView = QtGui.QTableView(self.tab_11)
        self.tableView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_14.addWidget(self.tableView)
        self.tabWidget_4.addTab(self.tab_11, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_12)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.splitter_7 = QtGui.QSplitter(self.tab_12)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.frame_23 = QtGui.QFrame(self.splitter_7)
        self.frame_23.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_23.setObjectName(_fromUtf8("frame_23"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.frame_23)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.statistical_characterization_treeview = QtGui.QTreeView(self.frame_23)
        self.statistical_characterization_treeview.setObjectName(_fromUtf8("statistical_characterization_treeview"))
        self.verticalLayout_18.addWidget(self.statistical_characterization_treeview)
        self.frame_25 = QtGui.QFrame(self.frame_23)
        self.frame_25.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_25.setObjectName(_fromUtf8("frame_25"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.frame_25)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.calculate_data_characterization_button = QtGui.QPushButton(self.frame_25)
        self.calculate_data_characterization_button.setObjectName(_fromUtf8("calculate_data_characterization_button"))
        self.verticalLayout_17.addWidget(self.calculate_data_characterization_button)
        self.verticalLayout_18.addWidget(self.frame_25)
        self.frame_24 = QtGui.QFrame(self.splitter_7)
        self.frame_24.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_24.setObjectName(_fromUtf8("frame_24"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frame_24)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.statisticalGridPlot = MatplotlibWidget(self.frame_24)
        self.statisticalGridPlot.setObjectName(_fromUtf8("statisticalGridPlot"))
        self.verticalLayout_15.addWidget(self.statisticalGridPlot)
        self.verticalLayout_16.addWidget(self.splitter_7)
        self.tabWidget_4.addTab(self.tab_12, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget_4)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(0, 5)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_memory_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.widget, icon8, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame_4 = QtGui.QFrame(self.splitter_2)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setMargin(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget_5 = QtGui.QTabWidget(self.frame_4)
        self.tabWidget_5.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_5.setObjectName(_fromUtf8("tabWidget_5"))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.tab_13)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_15 = QtGui.QLabel(self.tab_13)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_19.addWidget(self.label_15)
        self.results_time_selection_comboBox = QtGui.QComboBox(self.tab_13)
        self.results_time_selection_comboBox.setObjectName(_fromUtf8("results_time_selection_comboBox"))
        self.verticalLayout_19.addWidget(self.results_time_selection_comboBox)
        self.label_16 = QtGui.QLabel(self.tab_13)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_19.addWidget(self.label_16)
        self.pf_results_treeView = QtGui.QTreeView(self.tab_13)
        self.pf_results_treeView.setObjectName(_fromUtf8("pf_results_treeView"))
        self.verticalLayout_19.addWidget(self.pf_results_treeView)
        self.tabWidget_5.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_14)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_56 = QtGui.QLabel(self.tab_14)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.verticalLayout_11.addWidget(self.label_56)
        self.sta_results_treeView = QtGui.QTreeView(self.tab_14)
        self.sta_results_treeView.setObjectName(_fromUtf8("sta_results_treeView"))
        self.verticalLayout_11.addWidget(self.sta_results_treeView)
        self.tabWidget_5.addTab(self.tab_14, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.tab_15)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_57 = QtGui.QLabel(self.tab_15)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.verticalLayout_20.addWidget(self.label_57)
        self.ts_results_treeView = QtGui.QTreeView(self.tab_15)
        self.ts_results_treeView.setObjectName(_fromUtf8("ts_results_treeView"))
        self.verticalLayout_20.addWidget(self.ts_results_treeView)
        self.legend_ts_checkBox = QtGui.QCheckBox(self.tab_15)
        self.legend_ts_checkBox.setObjectName(_fromUtf8("legend_ts_checkBox"))
        self.verticalLayout_20.addWidget(self.legend_ts_checkBox)
        self.box_whiskers_ts_checkBox = QtGui.QCheckBox(self.tab_15)
        self.box_whiskers_ts_checkBox.setObjectName(_fromUtf8("box_whiskers_ts_checkBox"))
        self.verticalLayout_20.addWidget(self.box_whiskers_ts_checkBox)
        self.tabWidget_5.addTab(self.tab_15, _fromUtf8(""))
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.tab_16)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_58 = QtGui.QLabel(self.tab_16)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.verticalLayout_21.addWidget(self.label_58)
        self.sto_results_treeView = QtGui.QTreeView(self.tab_16)
        self.sto_results_treeView.setObjectName(_fromUtf8("sto_results_treeView"))
        self.verticalLayout_21.addWidget(self.sto_results_treeView)
        self.legend_sto_checkBox = QtGui.QCheckBox(self.tab_16)
        self.legend_sto_checkBox.setObjectName(_fromUtf8("legend_sto_checkBox"))
        self.verticalLayout_21.addWidget(self.legend_sto_checkBox)
        self.box_whiskers_sto_checkBox = QtGui.QCheckBox(self.tab_16)
        self.box_whiskers_sto_checkBox.setObjectName(_fromUtf8("box_whiskers_sto_checkBox"))
        self.verticalLayout_21.addWidget(self.box_whiskers_sto_checkBox)
        self.tabWidget_5.addTab(self.tab_16, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget_5, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.resultsPlot = MatplotlibWidget(self.splitter)
        self.resultsPlot.setObjectName(_fromUtf8("resultsPlot"))
        self.frame_5 = QtGui.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.resultsTableView = QtGui.QTableView(self.frame_5)
        self.resultsTableView.setObjectName(_fromUtf8("resultsTableView"))
        self.gridLayout_2.addWidget(self.resultsTableView, 0, 0, 1, 3)
        self.saveResultsButton = QtGui.QPushButton(self.frame_5)
        self.saveResultsButton.setObjectName(_fromUtf8("saveResultsButton"))
        self.gridLayout_2.addWidget(self.saveResultsButton, 1, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_insert_chart_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon9, _fromUtf8(""))
        self.console_tab = QtGui.QWidget()
        self.console_tab.setObjectName(_fromUtf8("console_tab"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.console_tab)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.tabWidget.addTab(self.console_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.progress_frame = QtGui.QFrame(self.centralwidget)
        self.progress_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.progress_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.progress_frame.setObjectName(_fromUtf8("progress_frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.progress_frame)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cancelButton = QtGui.QPushButton(self.progress_frame)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.progressBar = QtGui.QProgressBar(self.progress_frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.progress_frame)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1153, 28))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuProject = QtGui.QMenu(self.menuBar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuGrid = QtGui.QMenu(self.menuBar)
        self.menuGrid.setObjectName(_fromUtf8("menuGrid"))
        self.menuCreate_Branch_Type = QtGui.QMenu(self.menuGrid)
        self.menuCreate_Branch_Type.setObjectName(_fromUtf8("menuCreate_Branch_Type"))
        self.menuGraph = QtGui.QMenu(self.menuBar)
        self.menuGraph.setObjectName(_fromUtf8("menuGraph"))
        self.menuSimulations = QtGui.QMenu(self.menuBar)
        self.menuSimulations.setObjectName(_fromUtf8("menuSimulations"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        mainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(mainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRedraw = QtGui.QAction(mainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_autorenew_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedraw.setIcon(icon10)
        self.actionRedraw.setObjectName(_fromUtf8("actionRedraw"))
        self.actionLine = QtGui.QAction(mainWindow)
        self.actionLine.setObjectName(_fromUtf8("actionLine"))
        self.actionTransformer = QtGui.QAction(mainWindow)
        self.actionTransformer.setObjectName(_fromUtf8("actionTransformer"))
        self.actionLine_type = QtGui.QAction(mainWindow)
        self.actionLine_type.setObjectName(_fromUtf8("actionLine_type"))
        self.actionTransformer_type = QtGui.QAction(mainWindow)
        self.actionTransformer_type.setObjectName(_fromUtf8("actionTransformer_type"))
        self.actionOpen_file = QtGui.QAction(mainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_file_upload_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_file.setIcon(icon11)
        self.actionOpen_file.setObjectName(_fromUtf8("actionOpen_file"))
        self.actionSave = QtGui.QAction(mainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_file_download_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon12)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionImport = QtGui.QAction(mainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionExport = QtGui.QAction(mainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionNew_project = QtGui.QAction(mainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_insert_drive_file_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_project.setIcon(icon13)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionColor_by_type = QtGui.QAction(mainWindow)
        self.actionColor_by_type.setCheckable(True)
        self.actionColor_by_type.setChecked(True)
        self.actionColor_by_type.setObjectName(_fromUtf8("actionColor_by_type"))
        self.actionColor_by_results = QtGui.QAction(mainWindow)
        self.actionColor_by_results.setObjectName(_fromUtf8("actionColor_by_results"))
        self.actionPower_flow = QtGui.QAction(mainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_polymer_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_flow.setIcon(icon14)
        self.actionPower_flow.setObjectName(_fromUtf8("actionPower_flow"))
        self.actionPower_Flow_Time_series = QtGui.QAction(mainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/timeseriesicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_Flow_Time_series.setIcon(icon15)
        self.actionPower_Flow_Time_series.setObjectName(_fromUtf8("actionPower_Flow_Time_series"))
        self.actionBlackout = QtGui.QAction(mainWindow)
        self.actionBlackout.setObjectName(_fromUtf8("actionBlackout"))
        self.actionMove_node_Up = QtGui.QAction(mainWindow)
        self.actionMove_node_Up.setObjectName(_fromUtf8("actionMove_node_Up"))
        self.actionMove_node_Down = QtGui.QAction(mainWindow)
        self.actionMove_node_Down.setObjectName(_fromUtf8("actionMove_node_Down"))
        self.actionMove_node_Left = QtGui.QAction(mainWindow)
        self.actionMove_node_Left.setObjectName(_fromUtf8("actionMove_node_Left"))
        self.actionMove_node_Right = QtGui.QAction(mainWindow)
        self.actionMove_node_Right.setObjectName(_fromUtf8("actionMove_node_Right"))
        self.actionBus_voltages = QtGui.QAction(mainWindow)
        self.actionBus_voltages.setObjectName(_fromUtf8("actionBus_voltages"))
        self.actionBranches_current = QtGui.QAction(mainWindow)
        self.actionBranches_current.setObjectName(_fromUtf8("actionBranches_current"))
        self.actionBranches_loading = QtGui.QAction(mainWindow)
        self.actionBranches_loading.setObjectName(_fromUtf8("actionBranches_loading"))
        self.actionBlackout_2 = QtGui.QAction(mainWindow)
        self.actionBlackout_2.setObjectName(_fromUtf8("actionBlackout_2"))
        self.actionBranches_losses = QtGui.QAction(mainWindow)
        self.actionBranches_losses.setObjectName(_fromUtf8("actionBranches_losses"))
        self.actionBus_voltages_p_u = QtGui.QAction(mainWindow)
        self.actionBus_voltages_p_u.setObjectName(_fromUtf8("actionBus_voltages_p_u"))
        self.actionBigger_nodes = QtGui.QAction(mainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_add_circle_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBigger_nodes.setIcon(icon16)
        self.actionBigger_nodes.setObjectName(_fromUtf8("actionBigger_nodes"))
        self.actionSmaller_nodes = QtGui.QAction(mainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_remove_circle_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSmaller_nodes.setIcon(icon17)
        self.actionSmaller_nodes.setObjectName(_fromUtf8("actionSmaller_nodes"))
        self.actionPower_flow_Stochastic = QtGui.QAction(mainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/stochastic_power_flow.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_flow_Stochastic.setIcon(icon18)
        self.actionPower_flow_Stochastic.setObjectName(_fromUtf8("actionPower_flow_Stochastic"))
        self.actionActivate_map = QtGui.QAction(mainWindow)
        self.actionActivate_map.setObjectName(_fromUtf8("actionActivate_map"))
        self.actionVoltage_p_u = QtGui.QAction(mainWindow)
        self.actionVoltage_p_u.setObjectName(_fromUtf8("actionVoltage_p_u"))
        self.actionCurrent_p_u = QtGui.QAction(mainWindow)
        self.actionCurrent_p_u.setObjectName(_fromUtf8("actionCurrent_p_u"))
        self.actionLoading = QtGui.QAction(mainWindow)
        self.actionLoading.setObjectName(_fromUtf8("actionLoading"))
        self.actionLosses = QtGui.QAction(mainWindow)
        self.actionLosses.setObjectName(_fromUtf8("actionLosses"))
        self.actionRedrawByType = QtGui.QAction(mainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/plot_gridA2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedrawByType.setIcon(icon19)
        self.actionRedrawByType.setObjectName(_fromUtf8("actionRedrawByType"))
        self.actionRedrawByResult = QtGui.QAction(mainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/plot_gridB2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedrawByResult.setIcon(icon20)
        self.actionRedrawByResult.setObjectName(_fromUtf8("actionRedrawByResult"))
        self.actionVoltage_stability = QtGui.QAction(mainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/continuation_power_flow.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVoltage_stability.setIcon(icon21)
        self.actionVoltage_stability.setObjectName(_fromUtf8("actionVoltage_stability"))
        self.actionAbout = QtGui.QAction(mainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuProject.addAction(self.actionNew_project)
        self.menuProject.addAction(self.actionOpen_file)
        self.menuProject.addAction(self.actionSave)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionImport)
        self.menuProject.addAction(self.actionExport)
        self.menuCreate_Branch_Type.addAction(self.actionLine_type)
        self.menuCreate_Branch_Type.addAction(self.actionTransformer_type)
        self.menuGrid.addAction(self.menuCreate_Branch_Type.menuAction())
        self.menuGraph.addAction(self.actionRedraw)
        self.menuGraph.addSeparator()
        self.menuGraph.addAction(self.actionBigger_nodes)
        self.menuGraph.addAction(self.actionSmaller_nodes)
        self.menuGraph.addSeparator()
        self.menuGraph.addAction(self.actionActivate_map)
        self.menuGraph.addAction(self.actionRedrawByType)
        self.menuGraph.addAction(self.actionRedrawByResult)
        self.menuSimulations.addAction(self.actionPower_flow)
        self.menuSimulations.addAction(self.actionPower_Flow_Time_series)
        self.menuSimulations.addAction(self.actionPower_flow_Stochastic)
        self.menuSimulations.addAction(self.actionBlackout)
        self.menuSimulations.addAction(self.actionVoltage_stability)
        self.menuAbout.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuGrid.menuAction())
        self.menuBar.addAction(self.menuGraph.menuAction())
        self.menuBar.addAction(self.menuSimulations.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNew_project)
        self.toolBar.addAction(self.actionOpen_file)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPower_flow)
        self.toolBar.addAction(self.actionVoltage_stability)
        self.toolBar.addAction(self.actionPower_Flow_Time_series)
        self.toolBar.addAction(self.actionPower_flow_Stochastic)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRedrawByType)
        self.toolBar.addAction(self.actionRedrawByResult)
        self.toolBar.addAction(self.actionSmaller_nodes)
        self.toolBar.addAction(self.actionBigger_nodes)
        self.toolBar.addSeparator()

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "GridCal", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("mainWindow", "Grid", None))
        self.label_3.setText(_translate("mainWindow", "Data structures", None))
        self.label_4.setText(_translate("mainWindow", "Data table", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("mainWindow", "Info", None))
        self.label_22.setText(_translate("mainWindow", "Reactive power (Q)", None))
        self.label_19.setText(_translate("mainWindow", "Voltage angle", None))
        self.label_21.setText(_translate("mainWindow", "Active power (P)", None))
        self.label_17.setText(_translate("mainWindow", "Voltage |V|", None))
        self.label_18.setText(_translate("mainWindow", "Base voltage", None))
        self.label_7.setText(_translate("mainWindow", "Name", None))
        self.label_29.setText(_translate("mainWindow", "p.u.", None))
        self.label_28.setText(_translate("mainWindow", "Voltage (min)", None))
        self.label_27.setText(_translate("mainWindow", "kV", None))
        self.label_26.setText(_translate("mainWindow", "p.u.", None))
        self.label_24.setText(_translate("mainWindow", "MW", None))
        self.label_35.setText(_translate("mainWindow", "p.u.", None))
        self.label_34.setText(_translate("mainWindow", "Susceptance (B)", None))
        self.label_20.setText(_translate("mainWindow", "Power demmand", None))
        self.label_36.setText(_translate("mainWindow", "Shunt", None))
        self.label_31.setText(_translate("mainWindow", "Voltage (max)", None))
        self.label_25.setText(_translate("mainWindow", "deg", None))
        self.label_23.setText(_translate("mainWindow", "MVAr", None))
        self.label_30.setText(_translate("mainWindow", "p.u.", None))
        self.label_32.setText(_translate("mainWindow", "Capacitance (G)", None))
        self.substation_slack_checkBox.setText(_translate("mainWindow", "Is a voltage refference", None))
        self.label_33.setText(_translate("mainWindow", "p.u.", None))
        self.label_47.setText(_translate("mainWindow", "General", None))
        self.substation_apply_changes_button.setText(_translate("mainWindow", "Apply changes", None))
        self.dispatchable_load_checkBox.setText(_translate("mainWindow", "Dispatchable", None))
        self.substation_fix_power_checkBox.setToolTip(_translate("mainWindow", "<html><head/><body><p>If checked, when simulating time profiles or stochastic processes, the power will remain unchanged.</p></body></html>", None))
        self.substation_fix_power_checkBox.setText(_translate("mainWindow", "Fix power", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("mainWindow", "Substations", None))
        self.connections_status.setText(_translate("mainWindow", "Is active", None))
        self.label_46.setText(_translate("mainWindow", "x", None))
        self.label_52.setText(_translate("mainWindow", "p.u.", None))
        self.label_42.setText(_translate("mainWindow", "r", None))
        self.connections_apply_changes_button.setText(_translate("mainWindow", "Apply changes", None))
        self.label_43.setText(_translate("mainWindow", "ratio", None))
        self.label_49.setText(_translate("mainWindow", "p.u.", None))
        self.label_44.setText(_translate("mainWindow", "Name", None))
        self.label_45.setText(_translate("mainWindow", "p.u.", None))
        self.label_41.setText(_translate("mainWindow", "Bus 1", None))
        self.label_37.setText(_translate("mainWindow", "p.u.", None))
        self.label_40.setText(_translate("mainWindow", "Bus 2", None))
        self.label_38.setText(_translate("mainWindow", "Nominal power", None))
        self.label_50.setText(_translate("mainWindow", "MW", None))
        self.label_51.setText(_translate("mainWindow", "b", None))
        self.cable_editor_button.setText(_translate("mainWindow", "Cable editor", None))
        self.line_editor_button.setText(_translate("mainWindow", "Line editor", None))
        self.transformer_editor_button.setText(_translate("mainWindow", "Transformer editor", None))
        self.label_48.setText(_translate("mainWindow", "General", None))
        self.label_54.setText(_translate("mainWindow", "Shift", None))
        self.label_53.setText(_translate("mainWindow", "p.u.", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("mainWindow", "Connections", None))
        self.label_76.setText(_translate("mainWindow", "MVAr", None))
        self.label_63.setText(_translate("mainWindow", "Pmin", None))
        self.label_62.setText(_translate("mainWindow", "Base power", None))
        self.label_61.setText(_translate("mainWindow", "Voltage |V|", None))
        self.label_71.setText(_translate("mainWindow", "MW", None))
        self.label_74.setText(_translate("mainWindow", "MVAr", None))
        self.label_75.setText(_translate("mainWindow", "Qmax", None))
        self.label_65.setText(_translate("mainWindow", "Name", None))
        self.label_68.setText(_translate("mainWindow", "MVA", None))
        self.label_59.setText(_translate("mainWindow", "Active power (P)", None))
        self.label_69.setText(_translate("mainWindow", "p.u.", None))
        self.label_67.setText(_translate("mainWindow", "Pmax", None))
        self.label_66.setText(_translate("mainWindow", "MW", None))
        self.label_77.setText(_translate("mainWindow", "Qmin", None))
        self.label_39.setText(_translate("mainWindow", "Bus", None))
        self.label_70.setText(_translate("mainWindow", "MW", None))
        self.label_78.setText(_translate("mainWindow", "Limits", None))
        self.label_60.setText(_translate("mainWindow", "Generation values", None))
        self.label_64.setText(_translate("mainWindow", "General", None))
        self.powerplants_apply_changes_button.setText(_translate("mainWindow", "Apply changes", None))
        self.powerplants_status.setText(_translate("mainWindow", "Is active", None))
        self.dispatchable_gen_checkBox.setText(_translate("mainWindow", "Dispatchable", None))
        self.powerplants_fix_power_checkBox.setToolTip(_translate("mainWindow", "<html><head/><body><p>If checked, when simulating time profiles or stochastic processes, the power will remain unchanged.</p></body></html>", None))
        self.powerplants_fix_power_checkBox.setText(_translate("mainWindow", "Fix power", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("mainWindow", "Power plants", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Grid data", None))
        self.label.setText(_translate("mainWindow", "Power flow", None))
        self.label_2.setText(_translate("mainWindow", "Solver", None))
        self.label_5.setText(_translate("mainWindow", "Precision", None))
        self.label_6.setText(_translate("mainWindow", "Max. Iterations", None))
        self.helm_retry_checkBox.setText(_translate("mainWindow", "Retry with", None))
        self.control_Q_checkBox.setText(_translate("mainWindow", "Control reactive power", None))
        self.auto_precision_checkBox.setText(_translate("mainWindow", "Automatic precision", None))
        self.remember_last_solution_checkBox.setText(_translate("mainWindow", "Initialize with the \n"
"last solution", None))
        self.freq_assesment_check.setText(_translate("mainWindow", "Frequency drop assesment", None))
        self.label_11.setText(_translate("mainWindow", "Time series power flow", None))
        self.autorepeat_checkBox.setText(_translate("mainWindow", "Auto repeat shorter profiles", None))
        self.label_14.setText(_translate("mainWindow", "Stochastic power flow", None))
        self.montecarlo_radioButton.setText(_translate("mainWindow", "Monte Carlo", None))
        self.stochastic_process_radioButton.setText(_translate("mainWindow", "Stochastic process", None))
        self.stochastic_collocation_radioButton.setText(_translate("mainWindow", "Stochastic Collocation", None))
        self.label_13.setText(_translate("mainWindow", "Max. Iterations", None))
        self.label_12.setText(_translate("mainWindow", "Precision", None))
        self.label_55.setText(_translate("mainWindow", "Group data by", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("mainWindow", "Settings", None))
        self.pushButton_3.setText(_translate("mainWindow", "PushButton", None))
        self.pushButton_4.setText(_translate("mainWindow", "PushButton", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("mainWindow", "Dynamics events", None))
        self.label_10.setText(_translate("mainWindow", "Selection", None))
        self.set_profile_state_button.setText(_translate("mainWindow", "set state", None))
        self.label_9.setText(_translate("mainWindow", "Display", None))
        self.visualizeGenButton.setText(_translate("mainWindow", "Generators", None))
        self.visualizeLoadsButton.setText(_translate("mainWindow", "Loads", None))
        self.label_8.setText(_translate("mainWindow", "Import", None))
        self.importGenButton.setText(_translate("mainWindow", "Generators", None))
        self.importLoadButton.setText(_translate("mainWindow", "Loads", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("mainWindow", "Data", None))
        self.calculate_data_characterization_button.setText(_translate("mainWindow", "Calculate", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("mainWindow", "Statistical characterization", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("mainWindow", "Time series / Data source", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("mainWindow", "Time events", None))
        self.label_15.setText(_translate("mainWindow", "Time select", None))
        self.label_16.setText(_translate("mainWindow", "Elements", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_13), _translate("mainWindow", "Power flow", None))
        self.label_56.setText(_translate("mainWindow", "Nodes", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_14), _translate("mainWindow", "Stability", None))
        self.label_57.setText(_translate("mainWindow", "Elements", None))
        self.legend_ts_checkBox.setText(_translate("mainWindow", "Legend", None))
        self.box_whiskers_ts_checkBox.setText(_translate("mainWindow", "Box and whiskers view", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_15), _translate("mainWindow", "Time series", None))
        self.label_58.setText(_translate("mainWindow", "Elements", None))
        self.legend_sto_checkBox.setText(_translate("mainWindow", "Legend", None))
        self.box_whiskers_sto_checkBox.setText(_translate("mainWindow", "Box and whiskers view", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_16), _translate("mainWindow", "Stochastic", None))
        self.saveResultsButton.setText(_translate("mainWindow", "Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.console_tab), _translate("mainWindow", "Console", None))
        self.cancelButton.setText(_translate("mainWindow", "Cancel", None))
        self.menuProject.setTitle(_translate("mainWindow", "Project", None))
        self.menuGrid.setTitle(_translate("mainWindow", "Grid", None))
        self.menuCreate_Branch_Type.setTitle(_translate("mainWindow", "Create Branch Type", None))
        self.menuGraph.setTitle(_translate("mainWindow", "Graph", None))
        self.menuSimulations.setTitle(_translate("mainWindow", "Simulations", None))
        self.menuAbout.setTitle(_translate("mainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar", None))
        self.actionRedraw.setText(_translate("mainWindow", "Redraw", None))
        self.actionRedraw.setShortcut(_translate("mainWindow", "Ctrl+Alt+R", None))
        self.actionLine.setText(_translate("mainWindow", "Add Line", None))
        self.actionLine.setToolTip(_translate("mainWindow", "Line", None))
        self.actionLine.setShortcut(_translate("mainWindow", "Alt+L", None))
        self.actionTransformer.setText(_translate("mainWindow", "Add Transformer", None))
        self.actionTransformer.setShortcut(_translate("mainWindow", "Alt+T", None))
        self.actionLine_type.setText(_translate("mainWindow", "Line type", None))
        self.actionLine_type.setShortcut(_translate("mainWindow", "Alt+L, Alt+T", None))
        self.actionTransformer_type.setText(_translate("mainWindow", "Transformer type", None))
        self.actionTransformer_type.setShortcut(_translate("mainWindow", "Alt+T, Alt+T", None))
        self.actionOpen_file.setText(_translate("mainWindow", "Open file", None))
        self.actionOpen_file.setShortcut(_translate("mainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("mainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("mainWindow", "Ctrl+S", None))
        self.actionImport.setText(_translate("mainWindow", "Import", None))
        self.actionExport.setText(_translate("mainWindow", "Export", None))
        self.actionNew_project.setText(_translate("mainWindow", "New project", None))
        self.actionNew_project.setShortcut(_translate("mainWindow", "Ctrl+N", None))
        self.actionColor_by_type.setText(_translate("mainWindow", "Color by type", None))
        self.actionColor_by_results.setText(_translate("mainWindow", "Color by results", None))
        self.actionPower_flow.setText(_translate("mainWindow", "Power Flow", None))
        self.actionPower_Flow_Time_series.setText(_translate("mainWindow", "Power Flow: Time series", None))
        self.actionBlackout.setText(_translate("mainWindow", "Blackout", None))
        self.actionMove_node_Up.setText(_translate("mainWindow", "Move node Up", None))
        self.actionMove_node_Up.setShortcut(_translate("mainWindow", "Ctrl+Up", None))
        self.actionMove_node_Down.setText(_translate("mainWindow", "Move node Down", None))
        self.actionMove_node_Down.setShortcut(_translate("mainWindow", "Ctrl+Down", None))
        self.actionMove_node_Left.setText(_translate("mainWindow", "Move node Left", None))
        self.actionMove_node_Left.setShortcut(_translate("mainWindow", "Ctrl+Left", None))
        self.actionMove_node_Right.setText(_translate("mainWindow", "Move node Right", None))
        self.actionMove_node_Right.setShortcut(_translate("mainWindow", "Ctrl+Right", None))
        self.actionBus_voltages.setText(_translate("mainWindow", "Bus voltages", None))
        self.actionBranches_current.setText(_translate("mainWindow", "Branches current", None))
        self.actionBranches_loading.setText(_translate("mainWindow", "Branches loading (%)", None))
        self.actionBlackout_2.setText(_translate("mainWindow", "Blackout", None))
        self.actionBranches_losses.setText(_translate("mainWindow", "Branches losses", None))
        self.actionBus_voltages_p_u.setText(_translate("mainWindow", "Bus voltages (p.u.)", None))
        self.actionBigger_nodes.setText(_translate("mainWindow", "Bigger nodes", None))
        self.actionSmaller_nodes.setText(_translate("mainWindow", "Smaller nodes", None))
        self.actionPower_flow_Stochastic.setText(_translate("mainWindow", "Power flow: Stochastic", None))
        self.actionActivate_map.setText(_translate("mainWindow", "Activate map", None))
        self.actionVoltage_p_u.setText(_translate("mainWindow", "Voltage (p.u.)", None))
        self.actionCurrent_p_u.setText(_translate("mainWindow", "Current (p.u.)", None))
        self.actionLoading.setText(_translate("mainWindow", "Loading (%)", None))
        self.actionLosses.setText(_translate("mainWindow", "Losses", None))
        self.actionRedrawByType.setText(_translate("mainWindow", "Redraw by type", None))
        self.actionRedrawByResult.setText(_translate("mainWindow", "Redraw by result", None))
        self.actionVoltage_stability.setText(_translate("mainWindow", "Voltage stability", None))
        self.actionAbout.setText(_translate("mainWindow", "About", None))

from .matplotlibwidget import MatplotlibWidget
from .icons_rc import *

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

