# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue Dec 29 15:06:20 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(933, 502)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.open_button = QtGui.QPushButton(self.frame_3)
        self.open_button.setObjectName(_fromUtf8("open_button"))
        self.horizontalLayout_3.addWidget(self.open_button)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.doit_button = QtGui.QPushButton(self.frame_3)
        self.doit_button.setObjectName(_fromUtf8("doit_button"))
        self.horizontalLayout_3.addWidget(self.doit_button)
        self.verticalLayout.addWidget(self.frame_3)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_4 = QtGui.QFrame(self.splitter)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame = QtGui.QFrame(self.frame_4)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.units_combobox = QtGui.QComboBox(self.frame)
        self.units_combobox.setObjectName(_fromUtf8("units_combobox"))
        self.horizontalLayout_5.addWidget(self.units_combobox)
        self.verticalLayout_5.addWidget(self.frame)
        self.sources_list = QtGui.QListView(self.frame_4)
        self.sources_list.setObjectName(_fromUtf8("sources_list"))
        self.verticalLayout_5.addWidget(self.sources_list)
        self.frame_6 = QtGui.QFrame(self.splitter)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_10 = QtGui.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.frame_10)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.autolink_button = QtGui.QPushButton(self.frame_10)
        self.autolink_button.setObjectName(_fromUtf8("autolink_button"))
        self.horizontalLayout_7.addWidget(self.autolink_button)
        self.clear_selection_button = QtGui.QPushButton(self.frame_10)
        self.clear_selection_button.setObjectName(_fromUtf8("clear_selection_button"))
        self.horizontalLayout_7.addWidget(self.clear_selection_button)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.assignation_table = QtGui.QTableView(self.frame_6)
        self.assignation_table.setObjectName(_fromUtf8("assignation_table"))
        self.verticalLayout_3.addWidget(self.assignation_table)
        self.frame_9 = QtGui.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout = QtGui.QGridLayout(self.frame_9)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        self.set_multiplier_button = QtGui.QPushButton(self.frame_9)
        self.set_multiplier_button.setObjectName(_fromUtf8("set_multiplier_button"))
        self.gridLayout.addWidget(self.set_multiplier_button, 0, 0, 1, 1)
        self.set_cosfi_button = QtGui.QPushButton(self.frame_9)
        self.set_cosfi_button.setObjectName(_fromUtf8("set_cosfi_button"))
        self.gridLayout.addWidget(self.set_cosfi_button, 0, 1, 1, 1)
        self.multSpinBox = QtGui.QDoubleSpinBox(self.frame_9)
        self.multSpinBox.setMinimum(-99999.0)
        self.multSpinBox.setMaximum(99999.0)
        self.multSpinBox.setObjectName(_fromUtf8("multSpinBox"))
        self.gridLayout.addWidget(self.multSpinBox, 0, 2, 1, 1)
        self.setQ_on_cosfi_checkbox = QtGui.QCheckBox(self.frame_9)
        self.setQ_on_cosfi_checkbox.setObjectName(_fromUtf8("setQ_on_cosfi_checkbox"))
        self.gridLayout.addWidget(self.setQ_on_cosfi_checkbox, 0, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter_3 = QtGui.QSplitter(self.tab_2)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.frame_8 = QtGui.QFrame(self.splitter_3)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tableView = QtGui.QTableView(self.frame_8)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_7.addWidget(self.tableView)
        self.PlotFrame = QtGui.QFrame(self.splitter_3)
        self.PlotFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.PlotFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.PlotFrame.setObjectName(_fromUtf8("PlotFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.PlotFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plotwidget = MatplotlibWidget(self.PlotFrame)
        self.plotwidget.setObjectName(_fromUtf8("plotwidget"))
        self.horizontalLayout.addWidget(self.plotwidget)
        self.horizontalLayout_4.addWidget(self.splitter_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.open_button.setText(_translate("Dialog", "Import", None))
        self.label_4.setText(_translate("Dialog", "Profiles", None))
        self.doit_button.setText(_translate("Dialog", "Do it", None))
        self.label.setText(_translate("Dialog", "Sources", None))
        self.label_5.setText(_translate("Dialog", "Units", None))
        self.label_3.setText(_translate("Dialog", "Asignation", None))
        self.autolink_button.setText(_translate("Dialog", "Auto-link", None))
        self.clear_selection_button.setText(_translate("Dialog", "Clear selection", None))
        self.set_multiplier_button.setText(_translate("Dialog", "Set multiplier", None))
        self.set_cosfi_button.setText(_translate("Dialog", "Set cos(φ)", None))
        self.setQ_on_cosfi_checkbox.setText(_translate("Dialog", "Set Q on Cos(φ)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Assignation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Plot", None))

from .matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

