# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1173, 723)
        mainWindow.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        mainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Program/GridCal_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setIconSize(QtCore.QSize(24, 24))
        mainWindow.setDocumentMode(False)
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.GridTab = QtWidgets.QWidget()
        self.GridTab.setObjectName("GridTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.GridTab)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.GridTab)
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_3.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_3.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_3.setDocumentMode(True)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.GridSectionTab = QtWidgets.QWidget()
        self.GridSectionTab.setObjectName("GridSectionTab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.GridSectionTab)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cascade_grid_splitter = QtWidgets.QSplitter(self.GridSectionTab)
        self.cascade_grid_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.cascade_grid_splitter.setObjectName("cascade_grid_splitter")
        self.cascade_menu = QtWidgets.QFrame(self.cascade_grid_splitter)
        self.cascade_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cascade_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cascade_menu.setObjectName("cascade_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cascade_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.cascade_menu)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.run_cascade_pushButton = QtWidgets.QPushButton(self.frame_11)
        self.run_cascade_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/file/run_cascade.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_cascade_pushButton.setIcon(icon1)
        self.run_cascade_pushButton.setObjectName("run_cascade_pushButton")
        self.horizontalLayout_3.addWidget(self.run_cascade_pushButton)
        self.run_cascade_step_pushButton = QtWidgets.QPushButton(self.frame_11)
        self.run_cascade_step_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/file/run_cascade_step.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_cascade_step_pushButton.setIcon(icon2)
        self.run_cascade_step_pushButton.setObjectName("run_cascade_step_pushButton")
        self.horizontalLayout_3.addWidget(self.run_cascade_step_pushButton)
        self.copy_cascade_step_pushButton = QtWidgets.QPushButton(self.frame_11)
        self.copy_cascade_step_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/file/ic_content_copy_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_cascade_step_pushButton.setIcon(icon3)
        self.copy_cascade_step_pushButton.setObjectName("copy_cascade_step_pushButton")
        self.horizontalLayout_3.addWidget(self.copy_cascade_step_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.clear_cascade_pushButton = QtWidgets.QPushButton(self.frame_11)
        self.clear_cascade_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/file/ic_clear_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_cascade_pushButton.setIcon(icon4)
        self.clear_cascade_pushButton.setObjectName("clear_cascade_pushButton")
        self.horizontalLayout_3.addWidget(self.clear_cascade_pushButton)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.label_27 = QtWidgets.QLabel(self.frame_10)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_5.addWidget(self.label_27)
        self.cascade_tableView = QtWidgets.QTableView(self.frame_10)
        self.cascade_tableView.setObjectName("cascade_tableView")
        self.verticalLayout_5.addWidget(self.cascade_tableView)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.frame_6 = QtWidgets.QFrame(self.cascade_grid_splitter)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.schematic_layout = QtWidgets.QHBoxLayout()
        self.schematic_layout.setObjectName("schematic_layout")
        self.horizontalLayout_6.addLayout(self.schematic_layout)
        self.horizontalLayout_5.addWidget(self.cascade_grid_splitter)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/file/grid_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.GridSectionTab, icon5, "")
        self.DataTab = QtWidgets.QWidget()
        self.DataTab.setObjectName("DataTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.DataTab)
        self.verticalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.DataTab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_25.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.splitter_8 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.frame_26 = QtWidgets.QFrame(self.splitter_8)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_3 = QtWidgets.QLabel(self.frame_26)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_24.addWidget(self.label_3)
        self.dataStructuresListView = QtWidgets.QListView(self.frame_26)
        self.dataStructuresListView.setObjectName("dataStructuresListView")
        self.verticalLayout_24.addWidget(self.dataStructuresListView)
        self.frame_27 = QtWidgets.QFrame(self.splitter_8)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_4 = QtWidgets.QLabel(self.frame_27)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_23.addWidget(self.label_4)
        self.dataStructureTableView = QtWidgets.QTableView(self.frame_27)
        self.dataStructureTableView.setObjectName("dataStructureTableView")
        self.verticalLayout_23.addWidget(self.dataStructureTableView)
        self.frame_12 = QtWidgets.QFrame(self.frame_27)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.setValueToColumnButton = QtWidgets.QPushButton(self.frame_12)
        self.setValueToColumnButton.setIcon(icon3)
        self.setValueToColumnButton.setObjectName("setValueToColumnButton")
        self.horizontalLayout_11.addWidget(self.setValueToColumnButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_23.addWidget(self.frame_12)
        self.verticalLayout_25.addWidget(self.splitter_8)
        self.verticalLayout_8.addWidget(self.frame_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/file/ic_border_all_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.DataTab, icon6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_18 = QtWidgets.QFrame(self.tab)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_26.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.simulationDataSplitter = QtWidgets.QSplitter(self.frame_18)
        self.simulationDataSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.simulationDataSplitter.setObjectName("simulationDataSplitter")
        self.frame_28 = QtWidgets.QFrame(self.simulationDataSplitter)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_30 = QtWidgets.QLabel(self.frame_28)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_27.addWidget(self.label_30)
        self.simulationDataStructuresListView = QtWidgets.QListView(self.frame_28)
        self.simulationDataStructuresListView.setObjectName("simulationDataStructuresListView")
        self.verticalLayout_27.addWidget(self.simulationDataStructuresListView)
        self.frame_19 = QtWidgets.QFrame(self.frame_28)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_12.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_12.setSpacing(1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.exportSimulationDataButton = QtWidgets.QPushButton(self.frame_19)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/file/ic_file_download_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportSimulationDataButton.setIcon(icon7)
        self.exportSimulationDataButton.setObjectName("exportSimulationDataButton")
        self.horizontalLayout_12.addWidget(self.exportSimulationDataButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout_27.addWidget(self.frame_19)
        self.frame_29 = QtWidgets.QFrame(self.simulationDataSplitter)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_31 = QtWidgets.QLabel(self.frame_29)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_28.addWidget(self.label_31)
        self.simulationDataStructureTableView = QtWidgets.QTableView(self.frame_29)
        self.simulationDataStructureTableView.setObjectName("simulationDataStructureTableView")
        self.verticalLayout_28.addWidget(self.simulationDataStructureTableView)
        self.verticalLayout_26.addWidget(self.simulationDataSplitter)
        self.horizontalLayout_7.addWidget(self.frame_18)
        self.tabWidget_3.addTab(self.tab, icon6, "")
        self.verticalLayout_9.addWidget(self.tabWidget_3)
        self.tabWidget.addTab(self.GridTab, icon5, "")
        self.SettingsTab = QtWidgets.QWidget()
        self.SettingsTab.setObjectName("SettingsTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SettingsTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.SettingsTab)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.frame_7)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.solver_comboBox = QtWidgets.QComboBox(self.frame_7)
        self.solver_comboBox.setObjectName("solver_comboBox")
        self.verticalLayout_7.addWidget(self.solver_comboBox)
        self.frame_13 = QtWidgets.QFrame(self.frame_7)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_13)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.tolerance_spinBox = QtWidgets.QSpinBox(self.frame_13)
        self.tolerance_spinBox.setMinimum(1)
        self.tolerance_spinBox.setMaximum(20)
        self.tolerance_spinBox.setProperty("value", 4)
        self.tolerance_spinBox.setObjectName("tolerance_spinBox")
        self.gridLayout_4.addWidget(self.tolerance_spinBox, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.max_iterations_spinBox = QtWidgets.QSpinBox(self.frame_13)
        self.max_iterations_spinBox.setMinimum(10)
        self.max_iterations_spinBox.setMaximum(300)
        self.max_iterations_spinBox.setProperty("value", 20)
        self.max_iterations_spinBox.setObjectName("max_iterations_spinBox")
        self.gridLayout_4.addWidget(self.max_iterations_spinBox, 2, 1, 1, 1)
        self.helm_retry_checkBox = QtWidgets.QCheckBox(self.frame_13)
        self.helm_retry_checkBox.setChecked(True)
        self.helm_retry_checkBox.setObjectName("helm_retry_checkBox")
        self.gridLayout_4.addWidget(self.helm_retry_checkBox, 4, 0, 1, 2)
        self.control_Q_checkBox = QtWidgets.QCheckBox(self.frame_13)
        self.control_Q_checkBox.setChecked(True)
        self.control_Q_checkBox.setObjectName("control_Q_checkBox")
        self.gridLayout_4.addWidget(self.control_Q_checkBox, 7, 0, 1, 2)
        self.auto_precision_checkBox = QtWidgets.QCheckBox(self.frame_13)
        self.auto_precision_checkBox.setObjectName("auto_precision_checkBox")
        self.gridLayout_4.addWidget(self.auto_precision_checkBox, 0, 0, 1, 2)
        self.retry_solver_comboBox = QtWidgets.QComboBox(self.frame_13)
        self.retry_solver_comboBox.setObjectName("retry_solver_comboBox")
        self.gridLayout_4.addWidget(self.retry_solver_comboBox, 5, 0, 1, 2)
        self.remember_last_solution_checkBox = QtWidgets.QCheckBox(self.frame_13)
        self.remember_last_solution_checkBox.setChecked(True)
        self.remember_last_solution_checkBox.setObjectName("remember_last_solution_checkBox")
        self.gridLayout_4.addWidget(self.remember_last_solution_checkBox, 6, 0, 1, 2)
        self.dispatch_storage_checkBox = QtWidgets.QCheckBox(self.frame_13)
        self.dispatch_storage_checkBox.setObjectName("dispatch_storage_checkBox")
        self.gridLayout_4.addWidget(self.dispatch_storage_checkBox, 8, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.line_2 = QtWidgets.QFrame(self.frame_7)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.frame_17 = QtWidgets.QFrame(self.SettingsTab)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.frame_17)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_19.addWidget(self.label_17)
        self.line_11 = QtWidgets.QFrame(self.frame_17)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_19.addWidget(self.line_11)
        self.label_29 = QtWidgets.QLabel(self.frame_17)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_19.addWidget(self.label_29)
        self.vs_max_iterations_spinBox = QtWidgets.QSpinBox(self.frame_17)
        self.vs_max_iterations_spinBox.setMinimum(1)
        self.vs_max_iterations_spinBox.setMaximum(300)
        self.vs_max_iterations_spinBox.setProperty("value", 20)
        self.vs_max_iterations_spinBox.setObjectName("vs_max_iterations_spinBox")
        self.verticalLayout_19.addWidget(self.vs_max_iterations_spinBox)
        self.start_vs_from_default_radioButton = QtWidgets.QRadioButton(self.frame_17)
        self.start_vs_from_default_radioButton.setChecked(True)
        self.start_vs_from_default_radioButton.setObjectName("start_vs_from_default_radioButton")
        self.verticalLayout_19.addWidget(self.start_vs_from_default_radioButton)
        self.label_18 = QtWidgets.QLabel(self.frame_17)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.alpha_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_17)
        self.alpha_doubleSpinBox.setProperty("value", 2.0)
        self.alpha_doubleSpinBox.setObjectName("alpha_doubleSpinBox")
        self.verticalLayout_19.addWidget(self.alpha_doubleSpinBox)
        self.start_vs_from_selected_radioButton = QtWidgets.QRadioButton(self.frame_17)
        self.start_vs_from_selected_radioButton.setObjectName("start_vs_from_selected_radioButton")
        self.verticalLayout_19.addWidget(self.start_vs_from_selected_radioButton)
        self.label_19 = QtWidgets.QLabel(self.frame_17)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_19.addWidget(self.label_19)
        self.vs_departure_comboBox = QtWidgets.QComboBox(self.frame_17)
        self.vs_departure_comboBox.setObjectName("vs_departure_comboBox")
        self.verticalLayout_19.addWidget(self.vs_departure_comboBox)
        self.label_20 = QtWidgets.QLabel(self.frame_17)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_19.addWidget(self.label_20)
        self.vs_target_comboBox = QtWidgets.QComboBox(self.frame_17)
        self.vs_target_comboBox.setObjectName("vs_target_comboBox")
        self.verticalLayout_19.addWidget(self.vs_target_comboBox)
        self.line_12 = QtWidgets.QFrame(self.frame_17)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_19.addWidget(self.line_12)
        self.label_23 = QtWidgets.QLabel(self.frame_17)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_19.addWidget(self.label_23)
        self.line_15 = QtWidgets.QFrame(self.frame_17)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_19.addWidget(self.line_15)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem4)
        self.horizontalLayout_4.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.SettingsTab)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.frame_16)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.line_10 = QtWidgets.QFrame(self.frame_16)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_13.addWidget(self.line_10)
        self.montecarlo_radioButton = QtWidgets.QRadioButton(self.frame_16)
        self.montecarlo_radioButton.setChecked(True)
        self.montecarlo_radioButton.setObjectName("montecarlo_radioButton")
        self.verticalLayout_13.addWidget(self.montecarlo_radioButton)
        self.frame_15 = QtWidgets.QFrame(self.frame_16)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tolerance_stochastic_spinBox = QtWidgets.QSpinBox(self.frame_15)
        self.tolerance_stochastic_spinBox.setMinimum(1)
        self.tolerance_stochastic_spinBox.setMaximum(20)
        self.tolerance_stochastic_spinBox.setProperty("value", 3)
        self.tolerance_stochastic_spinBox.setObjectName("tolerance_stochastic_spinBox")
        self.gridLayout_6.addWidget(self.tolerance_stochastic_spinBox, 3, 1, 1, 1)
        self.max_iterations_stochastic_spinBox = QtWidgets.QSpinBox(self.frame_15)
        self.max_iterations_stochastic_spinBox.setMinimum(10)
        self.max_iterations_stochastic_spinBox.setMaximum(99999999)
        self.max_iterations_stochastic_spinBox.setProperty("value", 1000)
        self.max_iterations_stochastic_spinBox.setObjectName("max_iterations_stochastic_spinBox")
        self.gridLayout_6.addWidget(self.max_iterations_stochastic_spinBox, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_15)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_15)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 3, 0, 1, 1)
        self.group_by_comboBox = QtWidgets.QComboBox(self.frame_15)
        self.group_by_comboBox.setObjectName("group_by_comboBox")
        self.gridLayout_6.addWidget(self.group_by_comboBox, 1, 0, 1, 2)
        self.label_55 = QtWidgets.QLabel(self.frame_15)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_15)
        self.line_13 = QtWidgets.QFrame(self.frame_16)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_13.addWidget(self.line_13)
        self.label_22 = QtWidgets.QLabel(self.frame_16)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.frame_3 = QtWidgets.QFrame(self.frame_16)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout.addWidget(self.label_25)
        self.lhs_samples_number_spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.lhs_samples_number_spinBox.setMinimum(1)
        self.lhs_samples_number_spinBox.setMaximum(999999999)
        self.lhs_samples_number_spinBox.setProperty("value", 100)
        self.lhs_samples_number_spinBox.setObjectName("lhs_samples_number_spinBox")
        self.horizontalLayout.addWidget(self.lhs_samples_number_spinBox)
        self.verticalLayout_13.addWidget(self.frame_3)
        self.line_14 = QtWidgets.QFrame(self.frame_16)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_13.addWidget(self.line_14)
        self.label_26 = QtWidgets.QLabel(self.frame_16)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_13.addWidget(self.label_26)
        self.label_28 = QtWidgets.QLabel(self.frame_16)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_13.addWidget(self.label_28)
        self.cascading_islands_spinBox = QtWidgets.QSpinBox(self.frame_16)
        self.cascading_islands_spinBox.setMinimum(1)
        self.cascading_islands_spinBox.setMaximum(999999)
        self.cascading_islands_spinBox.setProperty("value", 1)
        self.cascading_islands_spinBox.setObjectName("cascading_islands_spinBox")
        self.verticalLayout_13.addWidget(self.cascading_islands_spinBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem5)
        self.horizontalLayout_4.addWidget(self.frame_16)
        self.frame_14 = QtWidgets.QFrame(self.SettingsTab)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_14)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.line_8 = QtWidgets.QFrame(self.frame_14)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_12.addWidget(self.line_8)
        self.label_24 = QtWidgets.QLabel(self.frame_14)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_12.addWidget(self.label_24)
        self.automatic_layout_comboBox = QtWidgets.QComboBox(self.frame_14)
        self.automatic_layout_comboBox.setObjectName("automatic_layout_comboBox")
        self.verticalLayout_12.addWidget(self.automatic_layout_comboBox)
        self.line_9 = QtWidgets.QFrame(self.frame_14)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_12.addWidget(self.line_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.horizontalLayout_4.addWidget(self.frame_14)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/file/ic_settings_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.SettingsTab, icon8, "")
        self.TimeEventsTab = QtWidgets.QWidget()
        self.TimeEventsTab.setObjectName("TimeEventsTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.TimeEventsTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.TimeEventsTab)
        self.tabWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_4.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame = QtWidgets.QFrame(self.tab_11)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.profile_device_type_comboBox = QtWidgets.QComboBox(self.frame)
        self.profile_device_type_comboBox.setObjectName("profile_device_type_comboBox")
        self.gridLayout_5.addWidget(self.profile_device_type_comboBox, 1, 10, 1, 1)
        self.device_type_magnitude_comboBox = QtWidgets.QComboBox(self.frame)
        self.device_type_magnitude_comboBox.setObjectName("device_type_magnitude_comboBox")
        self.gridLayout_5.addWidget(self.device_type_magnitude_comboBox, 1, 12, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 6, 1, 2)
        self.profile_import_pushButton = QtWidgets.QPushButton(self.frame)
        self.profile_import_pushButton.setObjectName("profile_import_pushButton")
        self.gridLayout_5.addWidget(self.profile_import_pushButton, 1, 14, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 1, 4, 1, 1)
        self.delete_profiles_structure_pushButton = QtWidgets.QPushButton(self.frame)
        self.delete_profiles_structure_pushButton.setObjectName("delete_profiles_structure_pushButton")
        self.gridLayout_5.addWidget(self.delete_profiles_structure_pushButton, 1, 2, 1, 1)
        self.profile_time_selection_comboBox = QtWidgets.QComboBox(self.frame)
        self.profile_time_selection_comboBox.setObjectName("profile_time_selection_comboBox")
        self.gridLayout_5.addWidget(self.profile_time_selection_comboBox, 1, 6, 1, 1)
        self.set_profile_state_button = QtWidgets.QPushButton(self.frame)
        self.set_profile_state_button.setObjectName("set_profile_state_button")
        self.gridLayout_5.addWidget(self.set_profile_state_button, 1, 7, 1, 1)
        self.new_profiles_structure_pushButton = QtWidgets.QPushButton(self.frame)
        self.new_profiles_structure_pushButton.setObjectName("new_profiles_structure_pushButton")
        self.gridLayout_5.addWidget(self.new_profiles_structure_pushButton, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 10, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 12, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 1, 8, 1, 1)
        self.profile_display_pushButton = QtWidgets.QPushButton(self.frame)
        self.profile_display_pushButton.setObjectName("profile_display_pushButton")
        self.gridLayout_5.addWidget(self.profile_display_pushButton, 1, 13, 1, 1)
        self.edit_profiles_pushButton = QtWidgets.QPushButton(self.frame)
        self.edit_profiles_pushButton.setObjectName("edit_profiles_pushButton")
        self.gridLayout_5.addWidget(self.edit_profiles_pushButton, 1, 3, 1, 1)
        self.verticalLayout_14.addWidget(self.frame)
        self.tableView = QtWidgets.QTableView(self.tab_11)
        self.tableView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_14.addWidget(self.tableView)
        self.tabWidget_4.addTab(self.tab_11, "")
        self.verticalLayout_4.addWidget(self.tabWidget_4)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/file/ic_memory_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.TimeEventsTab, icon9, "")
        self.ResultsTab = QtWidgets.QWidget()
        self.ResultsTab.setObjectName("ResultsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ResultsTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.ResultsTab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_4 = QtWidgets.QFrame(self.splitter_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_3 = QtWidgets.QSplitter(self.frame_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.frame_8 = QtWidgets.QFrame(self.splitter_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.frame_8)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.result_listView = QtWidgets.QListView(self.frame_8)
        self.result_listView.setObjectName("result_listView")
        self.verticalLayout_6.addWidget(self.result_listView)
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.result_type_listView = QtWidgets.QListView(self.frame_8)
        self.result_type_listView.setObjectName("result_type_listView")
        self.verticalLayout_6.addWidget(self.result_type_listView)
        self.frame_9 = QtWidgets.QFrame(self.splitter_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.select_none_pushButton = QtWidgets.QPushButton(self.frame_9)
        self.select_none_pushButton.setObjectName("select_none_pushButton")
        self.gridLayout.addWidget(self.select_none_pushButton, 2, 0, 1, 1)
        self.select_all_pushButton = QtWidgets.QPushButton(self.frame_9)
        self.select_all_pushButton.setObjectName("select_all_pushButton")
        self.gridLayout.addWidget(self.select_all_pushButton, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 1)
        self.plot_pushButton = QtWidgets.QPushButton(self.frame_9)
        self.plot_pushButton.setObjectName("plot_pushButton")
        self.gridLayout.addWidget(self.plot_pushButton, 3, 0, 1, 2)
        self.result_element_selection_listView = QtWidgets.QListView(self.frame_9)
        self.result_element_selection_listView.setObjectName("result_element_selection_listView")
        self.gridLayout.addWidget(self.result_element_selection_listView, 1, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.splitter_3)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.resultsPlot = MatplotlibWidget(self.splitter)
        self.resultsPlot.setObjectName("resultsPlot")
        self.frame_5 = QtWidgets.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resultsTableView = QtWidgets.QTableView(self.frame_5)
        self.resultsTableView.setObjectName("resultsTableView")
        self.gridLayout_2.addWidget(self.resultsTableView, 0, 0, 1, 3)
        self.saveResultsButton = QtWidgets.QPushButton(self.frame_5)
        self.saveResultsButton.setObjectName("saveResultsButton")
        self.gridLayout_2.addWidget(self.saveResultsButton, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/file/ic_insert_chart_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.ResultsTab, icon10, "")
        self.console_tab = QtWidgets.QWidget()
        self.console_tab.setObjectName("console_tab")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.console_tab)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tabWidget.addTab(self.console_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.progress_frame = QtWidgets.QFrame(self.centralwidget)
        self.progress_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_frame.setObjectName("progress_frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.progress_frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.progressBar = QtWidgets.QProgressBar(self.progress_frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_7.addWidget(self.progressBar, 1, 2, 1, 1)
        self.progress_label = QtWidgets.QLabel(self.progress_frame)
        self.progress_label.setText("")
        self.progress_label.setObjectName("progress_label")
        self.gridLayout_7.addWidget(self.progress_label, 0, 2, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.progress_frame)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_7.addWidget(self.cancelButton, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.progress_frame)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1173, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuProject = QtWidgets.QMenu(self.menuBar)
        self.menuProject.setObjectName("menuProject")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        mainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRedraw = QtWidgets.QAction(mainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/file/ic_autorenew_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedraw.setIcon(icon11)
        self.actionRedraw.setObjectName("actionRedraw")
        self.actionLine = QtWidgets.QAction(mainWindow)
        self.actionLine.setObjectName("actionLine")
        self.actionTransformer = QtWidgets.QAction(mainWindow)
        self.actionTransformer.setObjectName("actionTransformer")
        self.actionLine_type = QtWidgets.QAction(mainWindow)
        self.actionLine_type.setObjectName("actionLine_type")
        self.actionTransformer_type = QtWidgets.QAction(mainWindow)
        self.actionTransformer_type.setObjectName("actionTransformer_type")
        self.actionOpen_file = QtWidgets.QAction(mainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/file/ic_file_upload_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_file.setIcon(icon12)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setIcon(icon7)
        self.actionSave.setObjectName("actionSave")
        self.actionImport = QtWidgets.QAction(mainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(mainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionNew_project = QtWidgets.QAction(mainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/file/ic_insert_drive_file_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_project.setIcon(icon13)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionColor_by_type = QtWidgets.QAction(mainWindow)
        self.actionColor_by_type.setCheckable(True)
        self.actionColor_by_type.setChecked(True)
        self.actionColor_by_type.setObjectName("actionColor_by_type")
        self.actionColor_by_results = QtWidgets.QAction(mainWindow)
        self.actionColor_by_results.setObjectName("actionColor_by_results")
        self.actionPower_flow = QtWidgets.QAction(mainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/file/ic_polymer_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_flow.setIcon(icon14)
        self.actionPower_flow.setObjectName("actionPower_flow")
        self.actionPower_Flow_Time_series = QtWidgets.QAction(mainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/file/timeseriesicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_Flow_Time_series.setIcon(icon15)
        self.actionPower_Flow_Time_series.setObjectName("actionPower_Flow_Time_series")
        self.actionBlackout = QtWidgets.QAction(mainWindow)
        self.actionBlackout.setObjectName("actionBlackout")
        self.actionMove_node_Up = QtWidgets.QAction(mainWindow)
        self.actionMove_node_Up.setObjectName("actionMove_node_Up")
        self.actionMove_node_Down = QtWidgets.QAction(mainWindow)
        self.actionMove_node_Down.setObjectName("actionMove_node_Down")
        self.actionMove_node_Left = QtWidgets.QAction(mainWindow)
        self.actionMove_node_Left.setObjectName("actionMove_node_Left")
        self.actionMove_node_Right = QtWidgets.QAction(mainWindow)
        self.actionMove_node_Right.setObjectName("actionMove_node_Right")
        self.actionBus_voltages = QtWidgets.QAction(mainWindow)
        self.actionBus_voltages.setObjectName("actionBus_voltages")
        self.actionBranches_current = QtWidgets.QAction(mainWindow)
        self.actionBranches_current.setObjectName("actionBranches_current")
        self.actionBranches_loading = QtWidgets.QAction(mainWindow)
        self.actionBranches_loading.setObjectName("actionBranches_loading")
        self.actionBlackout_2 = QtWidgets.QAction(mainWindow)
        self.actionBlackout_2.setObjectName("actionBlackout_2")
        self.actionBranches_losses = QtWidgets.QAction(mainWindow)
        self.actionBranches_losses.setObjectName("actionBranches_losses")
        self.actionBus_voltages_p_u = QtWidgets.QAction(mainWindow)
        self.actionBus_voltages_p_u.setObjectName("actionBus_voltages_p_u")
        self.actionBigger_nodes = QtWidgets.QAction(mainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/file/ic_add_circle_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBigger_nodes.setIcon(icon16)
        self.actionBigger_nodes.setObjectName("actionBigger_nodes")
        self.actionSmaller_nodes = QtWidgets.QAction(mainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/file/ic_remove_circle_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSmaller_nodes.setIcon(icon17)
        self.actionSmaller_nodes.setObjectName("actionSmaller_nodes")
        self.actionPower_flow_Stochastic = QtWidgets.QAction(mainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/file/stochastic_power_flow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_flow_Stochastic.setIcon(icon18)
        self.actionPower_flow_Stochastic.setObjectName("actionPower_flow_Stochastic")
        self.actionActivate_map = QtWidgets.QAction(mainWindow)
        self.actionActivate_map.setObjectName("actionActivate_map")
        self.actionVoltage_p_u = QtWidgets.QAction(mainWindow)
        self.actionVoltage_p_u.setObjectName("actionVoltage_p_u")
        self.actionCurrent_p_u = QtWidgets.QAction(mainWindow)
        self.actionCurrent_p_u.setObjectName("actionCurrent_p_u")
        self.actionLoading = QtWidgets.QAction(mainWindow)
        self.actionLoading.setObjectName("actionLoading")
        self.actionLosses = QtWidgets.QAction(mainWindow)
        self.actionLosses.setObjectName("actionLosses")
        self.actionVoltage_stability = QtWidgets.QAction(mainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/file/continuation_power_flow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVoltage_stability.setIcon(icon19)
        self.actionVoltage_stability.setObjectName("actionVoltage_stability")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCenter_view = QtWidgets.QAction(mainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/file/resize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenter_view.setIcon(icon20)
        self.actionCenter_view.setObjectName("actionCenter_view")
        self.actionShort_Circuit = QtWidgets.QAction(mainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/file/short_circuit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShort_Circuit.setIcon(icon21)
        self.actionShort_Circuit.setObjectName("actionShort_Circuit")
        self.actionAutoatic_layout = QtWidgets.QAction(mainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/file/automatic_layout.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoatic_layout.setIcon(icon22)
        self.actionAutoatic_layout.setObjectName("actionAutoatic_layout")
        self.actionLatin_Hypercube_Sampling = QtWidgets.QAction(mainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/file/latin_hypercube2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLatin_Hypercube_Sampling.setIcon(icon23)
        self.actionLatin_Hypercube_Sampling.setObjectName("actionLatin_Hypercube_Sampling")
        self.actionBlackout_cascade = QtWidgets.QAction(mainWindow)
        self.actionBlackout_cascade.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/file/blackout.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBlackout_cascade.setIcon(icon24)
        self.actionBlackout_cascade.setObjectName("actionBlackout_cascade")
        self.actionRun_complete_cascade = QtWidgets.QAction(mainWindow)
        self.actionRun_complete_cascade.setIcon(icon1)
        self.actionRun_complete_cascade.setObjectName("actionRun_complete_cascade")
        self.actionRun_cascade_step = QtWidgets.QAction(mainWindow)
        self.actionRun_cascade_step.setIcon(icon2)
        self.actionRun_cascade_step.setObjectName("actionRun_cascade_step")
        self.actionCopy_cascade_state_to_main_grid = QtWidgets.QAction(mainWindow)
        self.actionCopy_cascade_state_to_main_grid.setIcon(icon3)
        self.actionCopy_cascade_state_to_main_grid.setObjectName("actionCopy_cascade_state_to_main_grid")
        self.actionRevert_grid_to_initial_state = QtWidgets.QAction(mainWindow)
        self.actionRevert_grid_to_initial_state.setIcon(icon11)
        self.actionRevert_grid_to_initial_state.setObjectName("actionRevert_grid_to_initial_state")
        self.menuProject.addAction(self.actionNew_project)
        self.menuProject.addAction(self.actionOpen_file)
        self.menuProject.addAction(self.actionSave)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionExport)
        self.menuAbout.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNew_project)
        self.toolBar.addAction(self.actionOpen_file)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionRevert_grid_to_initial_state)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPower_flow)
        self.toolBar.addAction(self.actionShort_Circuit)
        self.toolBar.addAction(self.actionVoltage_stability)
        self.toolBar.addAction(self.actionPower_Flow_Time_series)
        self.toolBar.addAction(self.actionPower_flow_Stochastic)
        self.toolBar.addAction(self.actionLatin_Hypercube_Sampling)
        self.toolBar.addAction(self.actionBlackout_cascade)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSmaller_nodes)
        self.toolBar.addAction(self.actionBigger_nodes)
        self.toolBar.addAction(self.actionCenter_view)
        self.toolBar.addAction(self.actionAutoatic_layout)
        self.toolBar.addSeparator()

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "GridCal"))
        self.run_cascade_pushButton.setToolTip(_translate("mainWindow", "Run complete cascading process"))
        self.run_cascade_step_pushButton.setToolTip(_translate("mainWindow", "Run next cascading state"))
        self.copy_cascade_step_pushButton.setToolTip(_translate("mainWindow", "Copy cascade state to normal grid state"))
        self.label_27.setText(_translate("mainWindow", "Cascading steps"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.GridSectionTab), _translate("mainWindow", "Grid"))
        self.label_3.setText(_translate("mainWindow", "Data structures"))
        self.label_4.setText(_translate("mainWindow", "Data table"))
        self.setValueToColumnButton.setText(_translate("mainWindow", "Set value to column"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.DataTab), _translate("mainWindow", "Data"))
        self.label_30.setText(_translate("mainWindow", "Data structures"))
        self.exportSimulationDataButton.setText(_translate("mainWindow", "Export"))
        self.label_31.setText(_translate("mainWindow", "Data table"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("mainWindow", "Simulation data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GridTab), _translate("mainWindow", "Grid data"))
        self.label.setText(_translate("mainWindow", "Power flow"))
        self.label_2.setText(_translate("mainWindow", "Solver"))
        self.label_5.setText(_translate("mainWindow", "Precision"))
        self.label_6.setText(_translate("mainWindow", "Max. Iterations"))
        self.helm_retry_checkBox.setText(_translate("mainWindow", "Retry with"))
        self.control_Q_checkBox.setText(_translate("mainWindow", "Control reactive power"))
        self.auto_precision_checkBox.setText(_translate("mainWindow", "Automatic precision"))
        self.remember_last_solution_checkBox.setText(_translate("mainWindow", "Initialize with the \n"
"last solution"))
        self.dispatch_storage_checkBox.setText(_translate("mainWindow", "Dispatch storage"))
        self.label_17.setText(_translate("mainWindow", "Voltage stability"))
        self.label_29.setText(_translate("mainWindow", "Max. Iterations"))
        self.start_vs_from_default_radioButton.setText(_translate("mainWindow", "Use alpha target from current situation"))
        self.label_18.setText(_translate("mainWindow", "Alpha (Increase the power \'alpha\' times)"))
        self.start_vs_from_selected_radioButton.setText(_translate("mainWindow", "Use departure and target points from time series"))
        self.label_19.setText(_translate("mainWindow", "Now"))
        self.label_20.setText(_translate("mainWindow", "Target"))
        self.label_23.setText(_translate("mainWindow", "Time series power flow"))
        self.label_14.setText(_translate("mainWindow", "Stochastic power flow"))
        self.montecarlo_radioButton.setText(_translate("mainWindow", "Monte Carlo"))
        self.label_13.setText(_translate("mainWindow", "Max. Iterations"))
        self.label_12.setText(_translate("mainWindow", "Precision"))
        self.label_55.setText(_translate("mainWindow", "Group data by"))
        self.label_22.setText(_translate("mainWindow", "Latin Hypercube Sampling"))
        self.label_25.setText(_translate("mainWindow", "samples"))
        self.label_26.setText(_translate("mainWindow", "Cascading"))
        self.label_28.setText(_translate("mainWindow", "Aditional islands until stop"))
        self.label_11.setText(_translate("mainWindow", "Graphics"))
        self.label_24.setText(_translate("mainWindow", "Automatic layout"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SettingsTab), _translate("mainWindow", "Settings"))
        self.label_8.setText(_translate("mainWindow", "Profiles structure"))
        self.label_10.setText(_translate("mainWindow", "Time step"))
        self.profile_import_pushButton.setText(_translate("mainWindow", "Import"))
        self.delete_profiles_structure_pushButton.setText(_translate("mainWindow", "Delete"))
        self.set_profile_state_button.setText(_translate("mainWindow", "set state"))
        self.new_profiles_structure_pushButton.setText(_translate("mainWindow", "New"))
        self.label_9.setText(_translate("mainWindow", "Device type"))
        self.label_21.setText(_translate("mainWindow", "Magnitude"))
        self.profile_display_pushButton.setText(_translate("mainWindow", "Display"))
        self.edit_profiles_pushButton.setText(_translate("mainWindow", "Edit"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("mainWindow", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TimeEventsTab), _translate("mainWindow", "Time events"))
        self.label_16.setText(_translate("mainWindow", "Studies with results"))
        self.label_7.setText(_translate("mainWindow", "Types of results available in the study"))
        self.select_none_pushButton.setText(_translate("mainWindow", "None"))
        self.select_all_pushButton.setText(_translate("mainWindow", "All"))
        self.label_15.setText(_translate("mainWindow", "Devices"))
        self.plot_pushButton.setText(_translate("mainWindow", "Plot"))
        self.saveResultsButton.setText(_translate("mainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ResultsTab), _translate("mainWindow", "Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.console_tab), _translate("mainWindow", "Console"))
        self.cancelButton.setText(_translate("mainWindow", "Cancel"))
        self.menuProject.setTitle(_translate("mainWindow", "Project"))
        self.menuAbout.setTitle(_translate("mainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionRedraw.setText(_translate("mainWindow", "Redraw"))
        self.actionRedraw.setShortcut(_translate("mainWindow", "Ctrl+Alt+R"))
        self.actionLine.setText(_translate("mainWindow", "Add Line"))
        self.actionLine.setToolTip(_translate("mainWindow", "Line"))
        self.actionLine.setShortcut(_translate("mainWindow", "Alt+L"))
        self.actionTransformer.setText(_translate("mainWindow", "Add Transformer"))
        self.actionTransformer.setShortcut(_translate("mainWindow", "Alt+T"))
        self.actionLine_type.setText(_translate("mainWindow", "Line type"))
        self.actionLine_type.setShortcut(_translate("mainWindow", "Alt+L, Alt+T"))
        self.actionTransformer_type.setText(_translate("mainWindow", "Transformer type"))
        self.actionTransformer_type.setShortcut(_translate("mainWindow", "Alt+T, Alt+T"))
        self.actionOpen_file.setText(_translate("mainWindow", "Open file"))
        self.actionOpen_file.setShortcut(_translate("mainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("mainWindow", "Save"))
        self.actionSave.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.actionImport.setText(_translate("mainWindow", "Import"))
        self.actionExport.setText(_translate("mainWindow", "Export"))
        self.actionNew_project.setText(_translate("mainWindow", "New project"))
        self.actionNew_project.setShortcut(_translate("mainWindow", "Ctrl+N"))
        self.actionColor_by_type.setText(_translate("mainWindow", "Color by type"))
        self.actionColor_by_results.setText(_translate("mainWindow", "Color by results"))
        self.actionPower_flow.setText(_translate("mainWindow", "Power Flow"))
        self.actionPower_Flow_Time_series.setText(_translate("mainWindow", "Power Flow: Time series"))
        self.actionBlackout.setText(_translate("mainWindow", "Blackout"))
        self.actionMove_node_Up.setText(_translate("mainWindow", "Move node Up"))
        self.actionMove_node_Up.setShortcut(_translate("mainWindow", "Ctrl+Up"))
        self.actionMove_node_Down.setText(_translate("mainWindow", "Move node Down"))
        self.actionMove_node_Down.setShortcut(_translate("mainWindow", "Ctrl+Down"))
        self.actionMove_node_Left.setText(_translate("mainWindow", "Move node Left"))
        self.actionMove_node_Left.setShortcut(_translate("mainWindow", "Ctrl+Left"))
        self.actionMove_node_Right.setText(_translate("mainWindow", "Move node Right"))
        self.actionMove_node_Right.setShortcut(_translate("mainWindow", "Ctrl+Right"))
        self.actionBus_voltages.setText(_translate("mainWindow", "Bus voltages"))
        self.actionBranches_current.setText(_translate("mainWindow", "Branches current"))
        self.actionBranches_loading.setText(_translate("mainWindow", "Branches loading (%)"))
        self.actionBlackout_2.setText(_translate("mainWindow", "Blackout"))
        self.actionBranches_losses.setText(_translate("mainWindow", "Branches losses"))
        self.actionBus_voltages_p_u.setText(_translate("mainWindow", "Bus voltages (p.u.)"))
        self.actionBigger_nodes.setText(_translate("mainWindow", "Expand"))
        self.actionBigger_nodes.setToolTip(_translate("mainWindow", "Expand distances"))
        self.actionSmaller_nodes.setText(_translate("mainWindow", "Shrink"))
        self.actionSmaller_nodes.setToolTip(_translate("mainWindow", "Shrink distances"))
        self.actionPower_flow_Stochastic.setText(_translate("mainWindow", "Power flow: Stochastic"))
        self.actionActivate_map.setText(_translate("mainWindow", "Activate map"))
        self.actionVoltage_p_u.setText(_translate("mainWindow", "Voltage (p.u.)"))
        self.actionCurrent_p_u.setText(_translate("mainWindow", "Current (p.u.)"))
        self.actionLoading.setText(_translate("mainWindow", "Loading (%)"))
        self.actionLosses.setText(_translate("mainWindow", "Losses"))
        self.actionVoltage_stability.setText(_translate("mainWindow", "Voltage stability"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionCenter_view.setText(_translate("mainWindow", "center view"))
        self.actionShort_Circuit.setText(_translate("mainWindow", "Short Circuit"))
        self.actionAutoatic_layout.setText(_translate("mainWindow", "Autoatic layout"))
        self.actionAutoatic_layout.setToolTip(_translate("mainWindow", "Automatic layout the of the grid"))
        self.actionLatin_Hypercube_Sampling.setText(_translate("mainWindow", "Latin Hypercube Sampling"))
        self.actionLatin_Hypercube_Sampling.setToolTip(_translate("mainWindow", "Run Latin Hypercube Sampling"))
        self.actionBlackout_cascade.setText(_translate("mainWindow", "Blackout cascade"))
        self.actionBlackout_cascade.setToolTip(_translate("mainWindow", "Run a simulation or step by step blackout cascade"))
        self.actionRun_complete_cascade.setText(_translate("mainWindow", "run complete cascade"))
        self.actionRun_cascade_step.setText(_translate("mainWindow", "Run cascade step"))
        self.actionCopy_cascade_state_to_main_grid.setText(_translate("mainWindow", "Copy cascade state to main grid"))
        self.actionRevert_grid_to_initial_state.setText(_translate("mainWindow", "Revert grid to initial state"))
        self.actionRevert_grid_to_initial_state.setToolTip(_translate("mainWindow", "Revert grid to initial state"))

from .matplotlibwidget import MatplotlibWidget
from .icons_rc import *

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

