# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1045, 661)
        mainWindow.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        mainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Program/GridCal_icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setIconSize(QtCore.QSize(24, 24))
        mainWindow.setDocumentMode(False)
        mainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_9.setMargin(2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab)
        self.tabWidget_3.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.splitter_3 = QtGui.QSplitter(self.tab_6)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.frame_10 = QtGui.QFrame(self.splitter_3)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridPlot = MatplotlibWidget(self.frame_10)
        self.gridPlot.setObjectName(_fromUtf8("gridPlot"))
        self.verticalLayout_10.addWidget(self.gridPlot)
        self.frame_8 = QtGui.QFrame(self.splitter_3)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.item_table = QtGui.QTableView(self.frame_8)
        self.item_table.setObjectName(_fromUtf8("item_table"))
        self.verticalLayout_6.addWidget(self.item_table)
        self.frame_9 = QtGui.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.frame_9)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_mode_edit_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.horizontalLayout_6.addWidget(self.splitter_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/grid_icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_6, icon2, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frame_2 = QtGui.QFrame(self.tab_7)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.dataStructuresListView = QtGui.QListView(self.frame_2)
        self.dataStructuresListView.setObjectName(_fromUtf8("dataStructuresListView"))
        self.gridLayout_5.addWidget(self.dataStructuresListView, 1, 0, 1, 1)
        self.dataStructureTableView = QtGui.QTableView(self.frame_2)
        self.dataStructureTableView.setObjectName(_fromUtf8("dataStructureTableView"))
        self.gridLayout_5.addWidget(self.dataStructureTableView, 1, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 40)
        self.verticalLayout_8.addWidget(self.frame_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_border_all_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_7, icon3, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.tabWidget_3)
        self.tabWidget.addTab(self.tab, icon2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_7 = QtGui.QFrame(self.tab_5)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label = QtGui.QLabel(self.frame_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.line = QtGui.QFrame(self.frame_7)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.NR_option_button = QtGui.QRadioButton(self.frame_7)
        self.NR_option_button.setObjectName(_fromUtf8("NR_option_button"))
        self.verticalLayout_7.addWidget(self.NR_option_button)
        self.NR_Iwamoto_option_button = QtGui.QRadioButton(self.frame_7)
        self.NR_Iwamoto_option_button.setObjectName(_fromUtf8("NR_Iwamoto_option_button"))
        self.verticalLayout_7.addWidget(self.NR_Iwamoto_option_button)
        self.NRFD_option_button = QtGui.QRadioButton(self.frame_7)
        self.NRFD_option_button.setObjectName(_fromUtf8("NRFD_option_button"))
        self.verticalLayout_7.addWidget(self.NRFD_option_button)
        self.he_option_button = QtGui.QRadioButton(self.frame_7)
        self.he_option_button.setObjectName(_fromUtf8("he_option_button"))
        self.verticalLayout_7.addWidget(self.he_option_button)
        self.gs_option_button = QtGui.QRadioButton(self.frame_7)
        self.gs_option_button.setObjectName(_fromUtf8("gs_option_button"))
        self.verticalLayout_7.addWidget(self.gs_option_button)
        self.zbus_option_button = QtGui.QRadioButton(self.frame_7)
        self.zbus_option_button.setObjectName(_fromUtf8("zbus_option_button"))
        self.verticalLayout_7.addWidget(self.zbus_option_button)
        self.dc_option_button = QtGui.QRadioButton(self.frame_7)
        self.dc_option_button.setObjectName(_fromUtf8("dc_option_button"))
        self.verticalLayout_7.addWidget(self.dc_option_button)
        self.frame_13 = QtGui.QFrame(self.frame_7)
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_13)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.frame_13)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.tolerance_spinBox = QtGui.QSpinBox(self.frame_13)
        self.tolerance_spinBox.setMinimum(1)
        self.tolerance_spinBox.setMaximum(20)
        self.tolerance_spinBox.setProperty("value", 3)
        self.tolerance_spinBox.setObjectName(_fromUtf8("tolerance_spinBox"))
        self.gridLayout_4.addWidget(self.tolerance_spinBox, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_13)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.max_iterations_spinBox = QtGui.QSpinBox(self.frame_13)
        self.max_iterations_spinBox.setMinimum(10)
        self.max_iterations_spinBox.setMaximum(300)
        self.max_iterations_spinBox.setObjectName(_fromUtf8("max_iterations_spinBox"))
        self.gridLayout_4.addWidget(self.max_iterations_spinBox, 1, 1, 1, 1)
        self.remember_last_solution_checkBox = QtGui.QCheckBox(self.frame_13)
        self.remember_last_solution_checkBox.setChecked(True)
        self.remember_last_solution_checkBox.setObjectName(_fromUtf8("remember_last_solution_checkBox"))
        self.gridLayout_4.addWidget(self.remember_last_solution_checkBox, 2, 0, 1, 2)
        self.helm_retry_checkBox = QtGui.QCheckBox(self.frame_13)
        self.helm_retry_checkBox.setChecked(True)
        self.helm_retry_checkBox.setObjectName(_fromUtf8("helm_retry_checkBox"))
        self.gridLayout_4.addWidget(self.helm_retry_checkBox, 3, 0, 1, 2)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.line_2 = QtGui.QFrame(self.frame_7)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_7.addWidget(self.line_2)
        self.freq_assesment_check = QtGui.QCheckBox(self.frame_7)
        self.freq_assesment_check.setObjectName(_fromUtf8("freq_assesment_check"))
        self.verticalLayout_7.addWidget(self.freq_assesment_check)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.frame_14 = QtGui.QFrame(self.tab_5)
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_11 = QtGui.QLabel(self.frame_14)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_12.addWidget(self.label_11)
        self.line_8 = QtGui.QFrame(self.frame_14)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_12.addWidget(self.line_8)
        self.autorepeat_checkBox = QtGui.QCheckBox(self.frame_14)
        self.autorepeat_checkBox.setChecked(True)
        self.autorepeat_checkBox.setObjectName(_fromUtf8("autorepeat_checkBox"))
        self.verticalLayout_12.addWidget(self.autorepeat_checkBox)
        self.line_9 = QtGui.QFrame(self.frame_14)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_12.addWidget(self.line_9)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.frame_14)
        self.frame_16 = QtGui.QFrame(self.tab_5)
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_14 = QtGui.QLabel(self.frame_16)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_13.addWidget(self.label_14)
        self.line_10 = QtGui.QFrame(self.frame_16)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_13.addWidget(self.line_10)
        self.montecarlo_radioButton = QtGui.QRadioButton(self.frame_16)
        self.montecarlo_radioButton.setChecked(True)
        self.montecarlo_radioButton.setObjectName(_fromUtf8("montecarlo_radioButton"))
        self.verticalLayout_13.addWidget(self.montecarlo_radioButton)
        self.stochastic_process_radioButton = QtGui.QRadioButton(self.frame_16)
        self.stochastic_process_radioButton.setObjectName(_fromUtf8("stochastic_process_radioButton"))
        self.verticalLayout_13.addWidget(self.stochastic_process_radioButton)
        self.frame_15 = QtGui.QFrame(self.frame_16)
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_15)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tolerance_stochastic_spinBox = QtGui.QSpinBox(self.frame_15)
        self.tolerance_stochastic_spinBox.setMinimum(1)
        self.tolerance_stochastic_spinBox.setMaximum(20)
        self.tolerance_stochastic_spinBox.setProperty("value", 3)
        self.tolerance_stochastic_spinBox.setObjectName(_fromUtf8("tolerance_stochastic_spinBox"))
        self.gridLayout_6.addWidget(self.tolerance_stochastic_spinBox, 4, 1, 1, 1)
        self.max_iterations_stochastic_spinBox = QtGui.QSpinBox(self.frame_15)
        self.max_iterations_stochastic_spinBox.setMinimum(10)
        self.max_iterations_stochastic_spinBox.setMaximum(99999999)
        self.max_iterations_stochastic_spinBox.setProperty("value", 1000)
        self.max_iterations_stochastic_spinBox.setObjectName(_fromUtf8("max_iterations_stochastic_spinBox"))
        self.gridLayout_6.addWidget(self.max_iterations_stochastic_spinBox, 5, 1, 1, 1)
        self.line_13 = QtGui.QFrame(self.frame_15)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_6.addWidget(self.line_13, 3, 0, 1, 1)
        self.group_by_radioButton = QtGui.QRadioButton(self.frame_15)
        self.group_by_radioButton.setObjectName(_fromUtf8("group_by_radioButton"))
        self.gridLayout_6.addWidget(self.group_by_radioButton, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_15)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame_15)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 4, 0, 1, 1)
        self.group_by_comboBox = QtGui.QComboBox(self.frame_15)
        self.group_by_comboBox.setObjectName(_fromUtf8("group_by_comboBox"))
        self.gridLayout_6.addWidget(self.group_by_comboBox, 1, 1, 1, 1)
        self.use_complete_profile_radioButton = QtGui.QRadioButton(self.frame_15)
        self.use_complete_profile_radioButton.setChecked(True)
        self.use_complete_profile_radioButton.setObjectName(_fromUtf8("use_complete_profile_radioButton"))
        self.gridLayout_6.addWidget(self.use_complete_profile_radioButton, 0, 0, 1, 2)
        self.verticalLayout_13.addWidget(self.frame_15)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_4.addWidget(self.frame_16)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_settings_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon4, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget_2 = QtGui.QTabWidget(self.widget)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_6 = QtGui.QFrame(self.tab_4)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButton_3 = QtGui.QPushButton(self.frame_6)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.frame_6)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.tableView_2 = QtGui.QTableView(self.tab_4)
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.verticalLayout_3.addWidget(self.tableView_2)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setContentsMargins(0, 4, 0, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_3 = QtGui.QFrame(self.tab_3)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame = QtGui.QFrame(self.frame_3)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.set_profile_state_button = QtGui.QPushButton(self.frame)
        self.set_profile_state_button.setObjectName(_fromUtf8("set_profile_state_button"))
        self.horizontalLayout.addWidget(self.set_profile_state_button)
        self.profile_time_selection_comboBox = QtGui.QComboBox(self.frame)
        self.profile_time_selection_comboBox.setObjectName(_fromUtf8("profile_time_selection_comboBox"))
        self.horizontalLayout.addWidget(self.profile_time_selection_comboBox)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.line_7 = QtGui.QFrame(self.frame)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.visualizeGenButton = QtGui.QPushButton(self.frame)
        self.visualizeGenButton.setObjectName(_fromUtf8("visualizeGenButton"))
        self.horizontalLayout.addWidget(self.visualizeGenButton)
        self.visualizeLoadsButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualizeLoadsButton.sizePolicy().hasHeightForWidth())
        self.visualizeLoadsButton.setSizePolicy(sizePolicy)
        self.visualizeLoadsButton.setObjectName(_fromUtf8("visualizeLoadsButton"))
        self.horizontalLayout.addWidget(self.visualizeLoadsButton)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.importGenButton = QtGui.QPushButton(self.frame)
        self.importGenButton.setObjectName(_fromUtf8("importGenButton"))
        self.horizontalLayout.addWidget(self.importGenButton)
        self.importLoadButton = QtGui.QPushButton(self.frame)
        self.importLoadButton.setFlat(False)
        self.importLoadButton.setObjectName(_fromUtf8("importLoadButton"))
        self.horizontalLayout.addWidget(self.importLoadButton)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout_5.addWidget(self.frame)
        self.tableView = QtGui.QTableView(self.frame_3)
        self.tableView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_5.addWidget(self.tableView)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(0, 5)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_memory_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.widget, icon5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame_4 = QtGui.QFrame(self.splitter_2)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_12 = QtGui.QFrame(self.frame_4)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_12)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_2 = QtGui.QLabel(self.frame_12)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_11.addWidget(self.label_2)
        self.line_4 = QtGui.QFrame(self.frame_12)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_11.addWidget(self.line_4)
        self.results_time_selection_comboBox = QtGui.QComboBox(self.frame_12)
        self.results_time_selection_comboBox.setObjectName(_fromUtf8("results_time_selection_comboBox"))
        self.verticalLayout_11.addWidget(self.results_time_selection_comboBox)
        self.per_unit_voltages_Button = QtGui.QPushButton(self.frame_12)
        self.per_unit_voltages_Button.setObjectName(_fromUtf8("per_unit_voltages_Button"))
        self.verticalLayout_11.addWidget(self.per_unit_voltages_Button)
        self.branches_loading_Button = QtGui.QPushButton(self.frame_12)
        self.branches_loading_Button.setObjectName(_fromUtf8("branches_loading_Button"))
        self.verticalLayout_11.addWidget(self.branches_loading_Button)
        self.line_6 = QtGui.QFrame(self.frame_12)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_11.addWidget(self.line_6)
        self.label_7 = QtGui.QLabel(self.frame_12)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_11.addWidget(self.label_7)
        self.line_5 = QtGui.QFrame(self.frame_12)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_11.addWidget(self.line_5)
        self.per_unit_voltages_series_Button = QtGui.QPushButton(self.frame_12)
        self.per_unit_voltages_series_Button.setObjectName(_fromUtf8("per_unit_voltages_series_Button"))
        self.verticalLayout_11.addWidget(self.per_unit_voltages_series_Button)
        self.branches_loading_series_Button = QtGui.QPushButton(self.frame_12)
        self.branches_loading_series_Button.setObjectName(_fromUtf8("branches_loading_series_Button"))
        self.verticalLayout_11.addWidget(self.branches_loading_series_Button)
        self.boxplot_checkbox = QtGui.QCheckBox(self.frame_12)
        self.boxplot_checkbox.setObjectName(_fromUtf8("boxplot_checkbox"))
        self.verticalLayout_11.addWidget(self.boxplot_checkbox)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.gridLayout.addWidget(self.frame_12, 0, 0, 1, 1)
        self.frame_11 = QtGui.QFrame(self.frame_4)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout.addWidget(self.frame_11, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.resultsPlot = MatplotlibWidget(self.splitter)
        self.resultsPlot.setObjectName(_fromUtf8("resultsPlot"))
        self.frame_5 = QtGui.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 2, 1, 1)
        self.resultsTableView = QtGui.QTableView(self.frame_5)
        self.resultsTableView.setObjectName(_fromUtf8("resultsTableView"))
        self.gridLayout_2.addWidget(self.resultsTableView, 0, 0, 1, 3)
        self.copyResultsButton = QtGui.QPushButton(self.frame_5)
        self.copyResultsButton.setObjectName(_fromUtf8("copyResultsButton"))
        self.gridLayout_2.addWidget(self.copyResultsButton, 1, 0, 1, 1)
        self.saveResultsButton = QtGui.QPushButton(self.frame_5)
        self.saveResultsButton.setObjectName(_fromUtf8("saveResultsButton"))
        self.gridLayout_2.addWidget(self.saveResultsButton, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_insert_chart_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.progress_frame = QtGui.QFrame(self.centralwidget)
        self.progress_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.progress_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.progress_frame.setObjectName(_fromUtf8("progress_frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.progress_frame)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cancelButton = QtGui.QPushButton(self.progress_frame)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.progressBar = QtGui.QProgressBar(self.progress_frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.progress_frame)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1045, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuProject = QtGui.QMenu(self.menuBar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuGrid = QtGui.QMenu(self.menuBar)
        self.menuGrid.setObjectName(_fromUtf8("menuGrid"))
        self.menuCreate_Branch_Type = QtGui.QMenu(self.menuGrid)
        self.menuCreate_Branch_Type.setObjectName(_fromUtf8("menuCreate_Branch_Type"))
        self.menuGraph = QtGui.QMenu(self.menuBar)
        self.menuGraph.setObjectName(_fromUtf8("menuGraph"))
        self.menuSimulations = QtGui.QMenu(self.menuBar)
        self.menuSimulations.setObjectName(_fromUtf8("menuSimulations"))
        self.menuResults = QtGui.QMenu(self.menuBar)
        self.menuResults.setObjectName(_fromUtf8("menuResults"))
        self.menuSingle_power_flow = QtGui.QMenu(self.menuResults)
        self.menuSingle_power_flow.setObjectName(_fromUtf8("menuSingle_power_flow"))
        self.menuPower_flow_series = QtGui.QMenu(self.menuResults)
        self.menuPower_flow_series.setObjectName(_fromUtf8("menuPower_flow_series"))
        mainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(mainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRedraw = QtGui.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_autorenew_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedraw.setIcon(icon7)
        self.actionRedraw.setObjectName(_fromUtf8("actionRedraw"))
        self.actionAdd_node = QtGui.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/node_add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_node.setIcon(icon8)
        self.actionAdd_node.setIconVisibleInMenu(True)
        self.actionAdd_node.setObjectName(_fromUtf8("actionAdd_node"))
        self.actionLine = QtGui.QAction(mainWindow)
        self.actionLine.setObjectName(_fromUtf8("actionLine"))
        self.actionTransformer = QtGui.QAction(mainWindow)
        self.actionTransformer.setObjectName(_fromUtf8("actionTransformer"))
        self.actionLine_type = QtGui.QAction(mainWindow)
        self.actionLine_type.setObjectName(_fromUtf8("actionLine_type"))
        self.actionTransformer_type = QtGui.QAction(mainWindow)
        self.actionTransformer_type.setObjectName(_fromUtf8("actionTransformer_type"))
        self.actionOpen_file = QtGui.QAction(mainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_file_upload_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_file.setIcon(icon9)
        self.actionOpen_file.setObjectName(_fromUtf8("actionOpen_file"))
        self.actionSave = QtGui.QAction(mainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_file_download_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon10)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionImport = QtGui.QAction(mainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionExport = QtGui.QAction(mainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionNew_project = QtGui.QAction(mainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_insert_drive_file_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_project.setIcon(icon11)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionColor_by_type = QtGui.QAction(mainWindow)
        self.actionColor_by_type.setCheckable(True)
        self.actionColor_by_type.setChecked(True)
        self.actionColor_by_type.setObjectName(_fromUtf8("actionColor_by_type"))
        self.actionColor_by_results = QtGui.QAction(mainWindow)
        self.actionColor_by_results.setObjectName(_fromUtf8("actionColor_by_results"))
        self.actionPower_flow = QtGui.QAction(mainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_polymer_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_flow.setIcon(icon12)
        self.actionPower_flow.setObjectName(_fromUtf8("actionPower_flow"))
        self.actionPower_Flow_Time_series = QtGui.QAction(mainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/timeseriesicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_Flow_Time_series.setIcon(icon13)
        self.actionPower_Flow_Time_series.setObjectName(_fromUtf8("actionPower_Flow_Time_series"))
        self.actionBlackout = QtGui.QAction(mainWindow)
        self.actionBlackout.setObjectName(_fromUtf8("actionBlackout"))
        self.actionMove_node_Up = QtGui.QAction(mainWindow)
        self.actionMove_node_Up.setObjectName(_fromUtf8("actionMove_node_Up"))
        self.actionMove_node_Down = QtGui.QAction(mainWindow)
        self.actionMove_node_Down.setObjectName(_fromUtf8("actionMove_node_Down"))
        self.actionMove_node_Left = QtGui.QAction(mainWindow)
        self.actionMove_node_Left.setObjectName(_fromUtf8("actionMove_node_Left"))
        self.actionMove_node_Right = QtGui.QAction(mainWindow)
        self.actionMove_node_Right.setObjectName(_fromUtf8("actionMove_node_Right"))
        self.actionBus_voltages = QtGui.QAction(mainWindow)
        self.actionBus_voltages.setObjectName(_fromUtf8("actionBus_voltages"))
        self.actionBranches_current = QtGui.QAction(mainWindow)
        self.actionBranches_current.setObjectName(_fromUtf8("actionBranches_current"))
        self.actionBranches_loading = QtGui.QAction(mainWindow)
        self.actionBranches_loading.setObjectName(_fromUtf8("actionBranches_loading"))
        self.actionBlackout_2 = QtGui.QAction(mainWindow)
        self.actionBlackout_2.setObjectName(_fromUtf8("actionBlackout_2"))
        self.actionBranches_losses = QtGui.QAction(mainWindow)
        self.actionBranches_losses.setObjectName(_fromUtf8("actionBranches_losses"))
        self.actionBus_voltages_p_u = QtGui.QAction(mainWindow)
        self.actionBus_voltages_p_u.setObjectName(_fromUtf8("actionBus_voltages_p_u"))
        self.actionBigger_nodes = QtGui.QAction(mainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_add_circle_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBigger_nodes.setIcon(icon14)
        self.actionBigger_nodes.setObjectName(_fromUtf8("actionBigger_nodes"))
        self.actionSmaller_nodes = QtGui.QAction(mainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/ic_remove_circle_black_48dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSmaller_nodes.setIcon(icon15)
        self.actionSmaller_nodes.setObjectName(_fromUtf8("actionSmaller_nodes"))
        self.actionPower_flow_Stochastic = QtGui.QAction(mainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/stochastic_power_flow.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_flow_Stochastic.setIcon(icon16)
        self.actionPower_flow_Stochastic.setObjectName(_fromUtf8("actionPower_flow_Stochastic"))
        self.actionActivate_map = QtGui.QAction(mainWindow)
        self.actionActivate_map.setObjectName(_fromUtf8("actionActivate_map"))
        self.actionDelete_node = QtGui.QAction(mainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/node_del.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_node.setIcon(icon17)
        self.actionDelete_node.setObjectName(_fromUtf8("actionDelete_node"))
        self.actionAdd_branch = QtGui.QAction(mainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/branch_add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_branch.setIcon(icon18)
        self.actionAdd_branch.setObjectName(_fromUtf8("actionAdd_branch"))
        self.actionDelete_branch = QtGui.QAction(mainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/branch_del.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_branch.setIcon(icon19)
        self.actionDelete_branch.setObjectName(_fromUtf8("actionDelete_branch"))
        self.actionVoltage_p_u = QtGui.QAction(mainWindow)
        self.actionVoltage_p_u.setObjectName(_fromUtf8("actionVoltage_p_u"))
        self.actionCurrent_p_u = QtGui.QAction(mainWindow)
        self.actionCurrent_p_u.setObjectName(_fromUtf8("actionCurrent_p_u"))
        self.actionLoading = QtGui.QAction(mainWindow)
        self.actionLoading.setObjectName(_fromUtf8("actionLoading"))
        self.actionLosses = QtGui.QAction(mainWindow)
        self.actionLosses.setObjectName(_fromUtf8("actionLosses"))
        self.actionRedrawByType = QtGui.QAction(mainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/plot_gridA2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedrawByType.setIcon(icon20)
        self.actionRedrawByType.setObjectName(_fromUtf8("actionRedrawByType"))
        self.actionRedrawByResult = QtGui.QAction(mainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/plot_gridB2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedrawByResult.setIcon(icon21)
        self.actionRedrawByResult.setObjectName(_fromUtf8("actionRedrawByResult"))
        self.menuProject.addAction(self.actionNew_project)
        self.menuProject.addAction(self.actionOpen_file)
        self.menuProject.addAction(self.actionSave)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionImport)
        self.menuProject.addAction(self.actionExport)
        self.menuCreate_Branch_Type.addAction(self.actionLine_type)
        self.menuCreate_Branch_Type.addAction(self.actionTransformer_type)
        self.menuGrid.addAction(self.menuCreate_Branch_Type.menuAction())
        self.menuGraph.addAction(self.actionRedraw)
        self.menuGraph.addSeparator()
        self.menuGraph.addAction(self.actionBigger_nodes)
        self.menuGraph.addAction(self.actionSmaller_nodes)
        self.menuGraph.addSeparator()
        self.menuGraph.addAction(self.actionActivate_map)
        self.menuGraph.addAction(self.actionRedrawByType)
        self.menuGraph.addAction(self.actionRedrawByResult)
        self.menuSimulations.addAction(self.actionPower_flow)
        self.menuSimulations.addAction(self.actionPower_Flow_Time_series)
        self.menuSimulations.addAction(self.actionPower_flow_Stochastic)
        self.menuSimulations.addAction(self.actionBlackout)
        self.menuSingle_power_flow.addAction(self.actionBus_voltages)
        self.menuSingle_power_flow.addSeparator()
        self.menuSingle_power_flow.addAction(self.actionBranches_current)
        self.menuSingle_power_flow.addAction(self.actionBranches_losses)
        self.menuPower_flow_series.addSeparator()
        self.menuPower_flow_series.addAction(self.actionVoltage_p_u)
        self.menuPower_flow_series.addAction(self.actionCurrent_p_u)
        self.menuPower_flow_series.addAction(self.actionLoading)
        self.menuPower_flow_series.addAction(self.actionLosses)
        self.menuResults.addAction(self.menuSingle_power_flow.menuAction())
        self.menuResults.addSeparator()
        self.menuResults.addAction(self.menuPower_flow_series.menuAction())
        self.menuResults.addSeparator()
        self.menuResults.addAction(self.actionBlackout_2)
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuGrid.menuAction())
        self.menuBar.addAction(self.menuGraph.menuAction())
        self.menuBar.addAction(self.menuSimulations.menuAction())
        self.menuBar.addAction(self.menuResults.menuAction())
        self.toolBar.addAction(self.actionNew_project)
        self.toolBar.addAction(self.actionOpen_file)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPower_flow)
        self.toolBar.addAction(self.actionPower_Flow_Time_series)
        self.toolBar.addAction(self.actionPower_flow_Stochastic)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRedrawByType)
        self.toolBar.addAction(self.actionRedrawByResult)
        self.toolBar.addAction(self.actionSmaller_nodes)
        self.toolBar.addAction(self.actionBigger_nodes)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd_node)
        self.toolBar.addAction(self.actionDelete_node)
        self.toolBar.addAction(self.actionAdd_branch)
        self.toolBar.addAction(self.actionDelete_branch)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "GridCal", None))
        self.pushButton.setText(_translate("mainWindow", "Apply changes", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("mainWindow", "Grid", None))
        self.label_3.setText(_translate("mainWindow", "Data structures", None))
        self.label_4.setText(_translate("mainWindow", "Data table", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("mainWindow", "Info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Grid data", None))
        self.label.setText(_translate("mainWindow", "Power flow", None))
        self.NR_option_button.setText(_translate("mainWindow", "Newton Raphson", None))
        self.NR_Iwamoto_option_button.setText(_translate("mainWindow", "Newton Raphson Iwamoto", None))
        self.NRFD_option_button.setText(_translate("mainWindow", "Newton Raphson decoupled", None))
        self.he_option_button.setText(_translate("mainWindow", "Holomorphic embedding", None))
        self.gs_option_button.setText(_translate("mainWindow", "Gauss Seidel", None))
        self.zbus_option_button.setText(_translate("mainWindow", "ZBus", None))
        self.dc_option_button.setText(_translate("mainWindow", "DC approximation", None))
        self.label_5.setText(_translate("mainWindow", "Tolerance", None))
        self.label_6.setText(_translate("mainWindow", "Max. Iterations", None))
        self.remember_last_solution_checkBox.setText(_translate("mainWindow", "Initialize with the \n"
"last solution", None))
        self.helm_retry_checkBox.setText(_translate("mainWindow", "Retry with HELM if failed", None))
        self.freq_assesment_check.setText(_translate("mainWindow", "Frequency drop assesment", None))
        self.label_11.setText(_translate("mainWindow", "Time series power flow", None))
        self.autorepeat_checkBox.setText(_translate("mainWindow", "Auto repeat shorter profiles", None))
        self.label_14.setText(_translate("mainWindow", "Stochastic power flow", None))
        self.montecarlo_radioButton.setText(_translate("mainWindow", "Monte Carlo", None))
        self.stochastic_process_radioButton.setText(_translate("mainWindow", "Stochastic process", None))
        self.group_by_radioButton.setText(_translate("mainWindow", "Group data by:", None))
        self.label_13.setText(_translate("mainWindow", "Max. Iterations", None))
        self.label_12.setText(_translate("mainWindow", "Tolerance", None))
        self.use_complete_profile_radioButton.setText(_translate("mainWindow", "Use the complete profile", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("mainWindow", "Settings", None))
        self.pushButton_3.setText(_translate("mainWindow", "PushButton", None))
        self.pushButton_4.setText(_translate("mainWindow", "PushButton", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("mainWindow", "Dynamics events", None))
        self.set_profile_state_button.setText(_translate("mainWindow", "set state", None))
        self.label_10.setText(_translate("mainWindow", "Selection", None))
        self.visualizeGenButton.setText(_translate("mainWindow", "Generators", None))
        self.visualizeLoadsButton.setText(_translate("mainWindow", "Loads", None))
        self.label_9.setText(_translate("mainWindow", "Display", None))
        self.importGenButton.setText(_translate("mainWindow", "Generators", None))
        self.importLoadButton.setText(_translate("mainWindow", "Loads", None))
        self.label_8.setText(_translate("mainWindow", "Import", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("mainWindow", "Time series / Data source", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("mainWindow", "Time events", None))
        self.label_2.setText(_translate("mainWindow", "Power flow", None))
        self.per_unit_voltages_Button.setText(_translate("mainWindow", "Voltages p.u.", None))
        self.branches_loading_Button.setText(_translate("mainWindow", "Branch Loading (%)", None))
        self.label_7.setText(_translate("mainWindow", "Power flow: Time series", None))
        self.per_unit_voltages_series_Button.setText(_translate("mainWindow", "Voltages p.u.", None))
        self.branches_loading_series_Button.setText(_translate("mainWindow", "Branch Loading (%)", None))
        self.boxplot_checkbox.setText(_translate("mainWindow", "Box and whiskers plot", None))
        self.copyResultsButton.setText(_translate("mainWindow", "Copy", None))
        self.saveResultsButton.setText(_translate("mainWindow", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Results", None))
        self.cancelButton.setText(_translate("mainWindow", "Cancel", None))
        self.menuProject.setTitle(_translate("mainWindow", "Project", None))
        self.menuGrid.setTitle(_translate("mainWindow", "Grid", None))
        self.menuCreate_Branch_Type.setTitle(_translate("mainWindow", "Create Branch Type", None))
        self.menuGraph.setTitle(_translate("mainWindow", "Graph", None))
        self.menuSimulations.setTitle(_translate("mainWindow", "Simulations", None))
        self.menuResults.setTitle(_translate("mainWindow", "Results", None))
        self.menuSingle_power_flow.setTitle(_translate("mainWindow", "Single power flow", None))
        self.menuPower_flow_series.setTitle(_translate("mainWindow", "power flow series", None))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar", None))
        self.actionRedraw.setText(_translate("mainWindow", "Redraw", None))
        self.actionRedraw.setShortcut(_translate("mainWindow", "Ctrl+Alt+R", None))
        self.actionAdd_node.setText(_translate("mainWindow", "Add node", None))
        self.actionLine.setText(_translate("mainWindow", "Add Line", None))
        self.actionLine.setToolTip(_translate("mainWindow", "Line", None))
        self.actionLine.setShortcut(_translate("mainWindow", "Alt+L", None))
        self.actionTransformer.setText(_translate("mainWindow", "Add Transformer", None))
        self.actionTransformer.setShortcut(_translate("mainWindow", "Alt+T", None))
        self.actionLine_type.setText(_translate("mainWindow", "Line type", None))
        self.actionLine_type.setShortcut(_translate("mainWindow", "Alt+L, Alt+T", None))
        self.actionTransformer_type.setText(_translate("mainWindow", "Transformer type", None))
        self.actionTransformer_type.setShortcut(_translate("mainWindow", "Alt+T, Alt+T", None))
        self.actionOpen_file.setText(_translate("mainWindow", "Open file", None))
        self.actionOpen_file.setShortcut(_translate("mainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("mainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("mainWindow", "Ctrl+S", None))
        self.actionImport.setText(_translate("mainWindow", "Import", None))
        self.actionExport.setText(_translate("mainWindow", "Export", None))
        self.actionNew_project.setText(_translate("mainWindow", "New project", None))
        self.actionNew_project.setShortcut(_translate("mainWindow", "Ctrl+N", None))
        self.actionColor_by_type.setText(_translate("mainWindow", "Color by type", None))
        self.actionColor_by_results.setText(_translate("mainWindow", "Color by results", None))
        self.actionPower_flow.setText(_translate("mainWindow", "Power Flow", None))
        self.actionPower_Flow_Time_series.setText(_translate("mainWindow", "Power Flow: Time series", None))
        self.actionBlackout.setText(_translate("mainWindow", "Blackout", None))
        self.actionMove_node_Up.setText(_translate("mainWindow", "Move node Up", None))
        self.actionMove_node_Up.setShortcut(_translate("mainWindow", "Ctrl+Up", None))
        self.actionMove_node_Down.setText(_translate("mainWindow", "Move node Down", None))
        self.actionMove_node_Down.setShortcut(_translate("mainWindow", "Ctrl+Down", None))
        self.actionMove_node_Left.setText(_translate("mainWindow", "Move node Left", None))
        self.actionMove_node_Left.setShortcut(_translate("mainWindow", "Ctrl+Left", None))
        self.actionMove_node_Right.setText(_translate("mainWindow", "Move node Right", None))
        self.actionMove_node_Right.setShortcut(_translate("mainWindow", "Ctrl+Right", None))
        self.actionBus_voltages.setText(_translate("mainWindow", "Bus voltages", None))
        self.actionBranches_current.setText(_translate("mainWindow", "Branches current", None))
        self.actionBranches_loading.setText(_translate("mainWindow", "Branches loading (%)", None))
        self.actionBlackout_2.setText(_translate("mainWindow", "Blackout", None))
        self.actionBranches_losses.setText(_translate("mainWindow", "Branches losses", None))
        self.actionBus_voltages_p_u.setText(_translate("mainWindow", "Bus voltages (p.u.)", None))
        self.actionBigger_nodes.setText(_translate("mainWindow", "Bigger nodes", None))
        self.actionSmaller_nodes.setText(_translate("mainWindow", "Smaller nodes", None))
        self.actionPower_flow_Stochastic.setText(_translate("mainWindow", "Power flow: Stochastic", None))
        self.actionActivate_map.setText(_translate("mainWindow", "Activate map", None))
        self.actionDelete_node.setText(_translate("mainWindow", "Delete node", None))
        self.actionAdd_branch.setText(_translate("mainWindow", "Add branch", None))
        self.actionDelete_branch.setText(_translate("mainWindow", "Delete branch", None))
        self.actionVoltage_p_u.setText(_translate("mainWindow", "Voltage (p.u.)", None))
        self.actionCurrent_p_u.setText(_translate("mainWindow", "Current (p.u.)", None))
        self.actionLoading.setText(_translate("mainWindow", "Loading (%)", None))
        self.actionLosses.setText(_translate("mainWindow", "Losses", None))
        self.actionRedrawByType.setText(_translate("mainWindow", "Redraw by type", None))
        self.actionRedrawByResult.setText(_translate("mainWindow", "Redraw by result", None))

from .matplotlibwidget import MatplotlibWidget
from .icons_rc import *

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

